### ISSUE TITLE
enhance: Use Ansible to deploy many hosts based on yum install method from jd.com

### ISSUE THREAD

**Issue by hooklee2000** [cubefs/cubefs#1148]
To deploy multiple hosts , yum install method using Ansible from jd.com is very valuable. Currently it downloads from jd.com .
We need  to  modify it to use latest compiled result files.
To deploy  role monitor, we need to upload a 80MB file cfs-monitor.tar.gz (which including consul,grafana,prometheus binary program) to github .
Also change default port to avoid confict:
    console 80 to 17080，consul 8500 to 17085, grafana dashboard 80 to  17088，prometheus 9090 to  17090

**Comment by jadewang198510** [comment]
we will consider to support it in the future. @hooklee2000
