### ISSUE TITLE
metanode can't clear extent data in some case, which will  cause garbage data

### ISSUE THREAD

**Issue by Victor1319** [cubeFS/cubefs#1226]
**Describe the bug**
case1. when invoke `if err = mp.doDeleteMarkedInodes(&ek); err != nil {` fail, extent will only be sent to leader's chan, not pass raft
case 2, when delete old extent file`EXTENT_DEL_V2_`, it may remove wrong file, here is code, may be EXTENT_DEL_V2_9 will cause 
EXTENT_DEL_V2_10 deleted
```
for _, f := range infos {
		if f.IsDir() {
			continue
		}
		if !strings.HasPrefix(f.Name(), prefixDelExtent) {
			continue
		}
		if f.Name() <= fileName {
			// TODO Unhandled errors
			os.Remove(path.Join(mp.config.RootDir, f.Name()))
			continue/* a */
		}
		break
	}
```

**To Reproduce**
case1, just make than delete markInode faile, eg: stop the datanode after invoke truncate
case 2, invoke truncate operation many times, so there is more than `10 EXTENT_DEL_V2_` files created

**Comment by jadewang198510** [comment]
Resolve  in  V3.0.0。 URL:  https://github.com/cubeFS/cubefs/releases/tag/v3.0.0
