### ISSUE TITLE
The official website https://chubao.io was crashed

### ISSUE THREAD

**Issue by Huweicai** [cubeFS/cubefs#1280]
https://chubao.io/
![图片](https://user-images.githubusercontent.com/29170746/144371987-7f90a532-c909-40db-aa6d-209f4da94d20.png)

dig result
![图片](https://user-images.githubusercontent.com/29170746/144372079-6d017e10-7f20-4d25-98e2-3c6bec6fcd4c.png)

**Comment by Huweicai** [comment]
@shuoranliu

**Comment by mervinkid** [comment]
@Huweicai 

We are in the process of migrating the site, which is expected to be completed next week.
