### ISSUE TITLE
Bug report cfs-bcache服务内存持续增长被操作系统kill

### ISSUE THREAD

**Issue by hadeslong** [cubefs/cubefs#1422]
**Describe the bug**
cfs-bcache服务在使用过程中内存持续增长直到oom被操作系统kill

**Environment**
cfs 3.0.0

**To Reproduce**
均按照用户手册部署

**Expected behavior**
正常cfs-bcache进程内存应该不会无限制增长

**Additional context**

**Comment by zhangtianjiong** [comment]
你的使用场景是否如下：三副本卷启用了cfs-bcache。目前三副本卷的单个extent为128MB,cfs-bcache按照extent进行缓存。所以sync.Pool中对象池的大小为128MB。大量文件读后内存消耗比较多，后面会稳定下来，可能超过了你系统内存。你的测试环境系统内存是多大呢？
另外：目前有针对cfs-bcache内存的优化，只缓存指定大小的小文件。内存需求就没那么大了

**Comment by hadeslong** [comment]
> 你的使用场景是否如下：三副本卷启用了cfs-bcache。目前三副本卷的单个extent为128MB,cfs-bcache按照extent进行缓存。所以sync.Pool中对象池的大小为128MB。大量文件读后内存消耗比较多，后面会稳定下来，可能超过了你系统内存。你的测试环境系统内存是多大呢？ 另外：目前有针对cfs-bcache内存的优化，只缓存指定大小的小文件。内存需求就没那么大了@[hadeslong](https://github.com/hadeslong)

你好，我的使用场景是三副本，查看日志内存使用超过77G被操作系统kill，cfs-bcache配置中的cachesize只能控制磁盘占用空间，想问下目前如何缓存指定大小文件，从而控制内存的占用空间，谢谢

**Comment by zhangtianjiong** [comment]
> > 你的使用场景是否如下：三副本卷启用了cfs-bcache。目前三副本卷的单个extent为128MB,cfs-bcache按照extent进行缓存。所以sync.Pool中对象池的大小为128MB。大量文件读后内存消耗比较多，后面会稳定下来，可能超过了你系统内存。你的测试环境系统内存是多大呢？ 另外：目前有针对cfs-bcache内存的优化，只缓存指定大小的小文件。内存需求就没那么大了@[hadeslong](https://github.com/hadeslong)
> 
> 你好，我的使用场景是三副本，查看日志内存使用超过77G被操作系统kill，cfs-bcache配置中的cachesize只能控制磁盘占用空间，想问下目前如何缓存指定大小文件，从而控制内存的占用空间，谢谢 @zhangtianjiong
你好，这个优化还没提交到社区。对于3.0.0的cfs-bcache我们测试使用nvme ssd，内存稳定到20GB左右，当前你这边是否使用的hdd磁盘？

**Comment by zhangtianjiong** [comment]
> > 你的使用场景是否如下：三副本卷启用了cfs-bcache。目前三副本卷的单个extent为128MB,cfs-bcache按照extent进行缓存。所以sync.Pool中对象池的大小为128MB。大量文件读后内存消耗比较多，后面会稳定下来，可能超过了你系统内存。你的测试环境系统内存是多大呢？ 另外：目前有针对cfs-bcache内存的优化，只缓存指定大小的小文件。内存需求就没那么大了@[hadeslong](https://github.com/hadeslong)
> 
> 你好，我的使用场景是三副本，查看日志内存使用超过77G被操作系统kill，cfs-bcache配置中的cachesize只能控制磁盘占用空间，想问下目前如何缓存指定大小文件，从而控制内存的占用空间，谢谢 @zhangtianjiong

你好，这个优化还没提交到社区。对于3.0.0的cfs-bcache我们测试使用nvme ssd，内存稳定到20GB左右，当前你这边是否使用的hdd磁盘？

**Comment by hadeslong** [comment]
> > > 你的使用场景是否如下：三副本卷启用了cfs-bcache。目前三副本卷的单个extent为128MB,cfs-bcache按照extent进行缓存。所以sync.Pool中对象池的大小为128MB。大量文件读后内存消耗比较多，后面会稳定下来，可能超过了你系统内存。你的测试环境系统内存是多大呢？ 另外：目前有针对cfs-bcache内存的优化，只缓存指定大小的小文件。内存需求就没那么大了@[hadeslong](https://github.com/hadeslong)
> > 
> > 
> > 你好，我的使用场景是三副本，查看日志内存使用超过77G被操作系统kill，cfs-bcache配置中的cachesize只能控制磁盘占用空间，想问下目前如何缓存指定大小文件，从而控制内存的占用空间，谢谢 @zhangtianjiong
> 
> 你好，这个优化还没提交到社区。对于3.0.0的cfs-bcache我们测试使用nvme ssd，内存稳定到20GB左右，当前你这边是否使用的hdd磁盘？@[hadeslong](https://github.com/hadeslong)

嗯嗯，是的我这边用的是hdd磁盘

**Comment by zhangtianjiong** [comment]
> 



> > > > 你的使用场景是否如下：三副本卷启用了cfs-bcache。目前三副本卷的单个extent为128MB,cfs-bcache按照extent进行缓存。所以sync.Pool中对象池的大小为128MB。大量文件读后内存消耗比较多，后面会稳定下来，可能超过了你系统内存。你的测试环境系统内存是多大呢？ 另外：目前有针对cfs-bcache内存的优化，只缓存指定大小的小文件。内存需求就没那么大了@[hadeslong](https://github.com/hadeslong)
> > > 
> > > 
> > > 你好，我的使用场景是三副本，查看日志内存使用超过77G被操作系统kill，cfs-bcache配置中的cachesize只能控制磁盘占用空间，想问下目前如何缓存指定大小文件，从而控制内存的占用空间，谢谢 @zhangtianjiong
> > 
> > 
> > 你好，这个优化还没提交到社区。对于3.0.0的cfs-bcache我们测试使用nvme ssd，内存稳定到20GB左右，当前你这边是否使用的hdd磁盘？@[hadeslong](https://github.com/hadeslong)
> 
> 嗯嗯，是的我这边用的是hdd磁盘

明白，cache数据落盘到hdd io会影响到buffer对象放回sync.Pool的速度，会申请新的buffer对象，导致内存上涨。感谢你的反馈！另外一级cache主要用来作为ec卷的加速或跨机房的数据加速，可能对同机房的副本卷读加速没效果。

**Comment by hadeslong** [comment]
了解，谢谢

**Comment by leonrayang** [comment]
#1500
