### ISSUE TITLE
Achieve and maintain a Core Infrastructure Initiative

### ISSUE THREAD

**Issue by xiaochunhe** [cubefs/cubefs#1445]
achieve and maintain a Core Infrastructure Initiative [Best Practices Badge](https://bestpractices.coreinfrastructure.org/).
 
refer to
1. CNCF Graduation Criteria：https://github.com/cncf/toc/blob/main/process/graduation_criteria.md
2. Best Practices Criteria for Free/Libre and Open Source Software (FLOSS): https://github.com/coreinfrastructure/best-practices-badge/blob/main/doc/criteria.md#best-practices-criteria-for-freelibre-and-open-source-software-floss

**Comment by pengtianyue025** [comment]
done
https://bestpractices.coreinfrastructure.org/zh-CN/projects/6232#quality
