### ISSUE TITLE
One datanode is inactive

### ISSUE THREAD

**Issue by gamestart** [cubefs/cubefs#1448]
**Describe the bug**
one datanode is inactive , calico and datanode pods always restart ,  the host where the inactive datanode run 

**Environment**
Describe your server system version, kernel version
system version : centos 7.9
kernel version: 3.10.0-1160.el7.x86_64
kubernetes version: v1.21.6
docker version: 20.10.10
disk: HDD

**To Reproduce**

**Expected behavior**
cfs-server progress sometimes being killed because OOM.

**Additional context**

**Comment by jadewang198510** [comment]
We have assisted users to solve this problem online, not a bug. @gamestart
