### ISSUE TITLE
中文教程文档内yum安装地址更新

### ISSUE THREAD

**Issue by zphj1987** [cubefs/cubefs#1449]
## 问题描述：
通过中文文档的链接内的内容不是最新的，还是采用的之前的chubaofs的相关的地址
https://cubefs.readthedocs.io/zh_CN/latest/

## 具体问题：
https://cubefs.readthedocs.io/zh_CN/latest/user-guide/yum.html
里面yum进行安装的部分
```bash
$ yum install http://storage.jd.com/chubaofsrpm/latest/cfs-install-latest-el7.x86_64.rpm
$ cd /cfs/install
```
这个文档里面拿的是比较久的地址链接

github的首页的readme里面的内容是
```bash
yum install https://ocs-cn-north1.heytapcs.com/cubefs/cfs-install-latest-el7.x86_64.rpm
```

## 期望：
修正相关的文档

**Comment by xiaochunhe** [comment]
thank you，we will fix it asap
