### ISSUE TITLE
集群创建时间属性的增加

### ISSUE THREAD

**Issue by zphj1987** [cubefs/cubefs#1468]
需求描述：
我们在创建集群的时候可以指定一个属性的值"Name": "chubaofs01",这个可以去定义集群的名称，但是在集群维护的时候，可能需要进行创建时间的辨别

可能需要的场景：
- 1、需要在多台机器上面创建多个集群，原来创建的集群，新创建的集群，有时候需要看下创建时间
- 2、集群运行了多久了（虽然可以通过不变文件的修改时间来看）
- 3、误操作的时候的判断，原来创建的master，集群完全被重新格式化了，通过创建时间可以清楚判断

期望：
在创建集群后，自动增加一个创建时间的字段：
通过 `curl -v "http://192.168.0.101:17010/admin/getCluster"`  可以拿到集群的创建时间

**Comment by zphj1987** [comment]
卷的地方就有这个信息：
```bash
{
    "code": 0,
    "data": {
        "Authenticate": false,
        "AutoRepair": false,
        "Capacity": 10000,
        "CreateTime": "2022-07-12 10:46:34",
        "CrossZone": false,
```
但这个是卷的，希望有能查到集群的

**Comment by leonrayang** [comment]
> 需求描述： 我们在创建集群的时候可以指定一个属性的值"Name": "chubaofs01",这个可以去定义集群的名称，但是在集群维护的时候，可能需要进行创建时间的辨别
> 
> 可能需要的场景：
> 
> * 1、需要在多台机器上面创建多个集群，原来创建的集群，新创建的集群，有时候需要看下创建时间
> * 2、集群运行了多久了（虽然可以通过不变文件的修改时间来看）
> * 3、误操作的时候的判断，原来创建的master，集群完全被重新格式化了，通过创建时间可以清楚判断
> 
> 期望： 在创建集群后，自动增加一个创建时间的字段： 通过 `curl -v "http://192.168.0.101:17010/admin/getCluster"` 可以拿到集群的创建时间
-------------
可以的，我们会记录下来，也欢迎参与提pr修复。
