### ISSUE TITLE
文档创建卷的参数说明错误-replicaNum

### ISSUE THREAD

**Issue by zphj1987** [cubefs/cubefs#1470]
问题描述：
文档地址：
https://cubefs.readthedocs.io/zh_CN/latest/admin-api/master/volume.html

```bash
replicaNum | int | 初始化数据分片个数
```
这个参数并不是初始化数据分片的个数，应该是初始化副本的数目吧？

**Comment by leonrayang** [comment]
@bboyCH4

**Comment by zphj1987** [comment]
close
