### ISSUE TITLE
master的Raft心跳端口独立设置的需求

### ISSUE THREAD

**Issue by zphj1987** [cubefs/cubefs#1480]
需求描述：
运行cubefs版本3.0.0
关于心跳的设置是，"heartbeatPort":"5901","replicaPort":"5902" 这两个参数进行的设置，目前设置这个参数设置的是自己当前的节点的，也默认了其它master节点会用这个端口
```bash
cat log/master/output.log
2022/07/13 15:38:57 peers[["nodeID":"1","peerID":"0","priority":"0","type":"PeerNormal","heartbeatPort":"5905","ReplicaPort":"5902" "nodeID":"2","peerID":"0","priority":"0","type":"PeerNormal","heartbeatPort":"5905","ReplicaPort":"5902" "nodeID":"3","peerID":"0","priority":"0","type":"PeerNormal","heartbeatPort":"5905","ReplicaPort":"5902"]],tickInterval[500],electionTick[5]
2022/07/13 15:38:57 server start success, pid 5743, role master
```
可以看到，如果我改了端口，实际上是会默认去认为其它节点的这个端口也改了，这个地方能够按照peers里面的类似处理不
```bash
"peers": "1:192.168.0.101:17010,2:192.168.0.102:17010,3:192.168.0.103:17010",
```
这个端口是设置自己的，默认连其它也是这个
"heartbeatPort":"5901",
"replicaPort":"5902"
默认解析出来是下面的
如果改了下面这个peers，就以下面这个设定为准的，去处理心跳
"heartbeatPortpeers":"1:192.168.0.101:5905,2:192.168.0.102:5905,3:192.168.0.103:5905"
"ReplicaPortpeers":"1:192.168.0.101:5902,2:192.168.0.102:5902,3:192.168.0.103:5902"

或者有其它更好的方法也可以

就是支持这种方式的解析，那么每台master节点可以根据自己的需求去改任意端口，这个可以给端口设置带来灵活性，并且不破坏默认的简洁性

这个是基于我想在单节点运行三个master实例的需求（纯测试），但是因为这个心跳端口无法独立设置，好像目前没有太好的办法单节点运行三个master

**Comment by leonrayang** [comment]
单机测试，还是建议docker，统一端口对运维管控也比较友好

**Comment by zphj1987** [comment]
close
