### ISSUE TITLE
Document upgrade and downgrade processes

### ISSUE THREAD

**Issue by zamazan4ik** [cubefs/cubefs#1505]
Hi.

After reading the documentation it is not clear for me, how upgrade and downgrade processes should be performed over the solution. Could you please describe somewhere in the documentation:

- How to upgrade CubeFS to the newer version (hopefully with no downtime)
- How to downgrade CubeFS to the older version (hopefully with no downtime)
- Maybe some compatibility policies and notes between versions

Thanks in advance!

**Comment by leonrayang** [comment]
> Hi.
> 
> After reading the documentation it is not clear for me, how upgrade and downgrade processes should be performed over the solution. Could you please describe somewhere in the documentation:
> 
> * How to upgrade CubeFS to the newer version (hopefully with no downtime)
   **We recommend that upgrade according to sequece: master->datanode->metanode->client, check the status on each step. there's no downtime usally， the service will not be interupted usually.**

> * How to downgrade CubeFS to the older version (hopefully with no downtime)
  **Actually we didn't get the bad case need to downgrade,  I sugest just reverse the sequece**

> * Maybe some compatibility policies and notes between versions
  **In the release note we have figured the policies, thanks for you advice, the upgrade notice will be listed on the document**
> 
> Thanks in advance!

**Comment by zamazan4ik** [comment]
> Actually we didn't get the bad case need to downgrade, I sugest just reverse the sequece

Am I right that it could be performed with no downtime too?

By the way, would be great if you add an explicit note about the downgrade into the documentation.

**Comment by leonrayang** [comment]
> > Actually we didn't get the bad case need to downgrade, I sugest just reverse the sequece
> 
> Am I right that it could be performed with no downtime too?
> 
> By the way, would be great if you add an explicit note about the downgrade into the documentation.

can I understant your request in this way that you want stop the process, change the bin file and start again. Normally this behavior will not infunce the sevice because all the modules has the function of retry or quorum ability to guarante the data consistency . In terms of downgrading, can you explain the reason for this, and the version related information to us, we can review this behavior together

**Comment by zamazan4ik** [comment]
> In terms of downgrading, can you explain the reason for this, and the version related information to us, we can review this behavior together

Sure. We are investigating different technologies. And we are thinking about the case, what should we do with our setup if after the update something goes wrong with the setup. And possibility to perform a (zero-downtime) downgrade could be a big advantage.
