### ISSUE TITLE
partition alloc strategy consider about capacity between nodeset

### ISSUE THREAD

**Issue by Victor1319** [cubefs/cubefs#1518]
**Is your feature request related to a problem? Please describe.**
partition alloc strategy between nodeset is `Round-Robin`,  it will caused unbalanced problem between new nodeset and old nodeset.

**Describe the solution you'd like**
partition alloc strategy should consider nodeset's available capacity.

**Comment by leonrayang** [comment]
will be fixed in future release

**Comment by Sush-Dew** [comment]
@Victor1319 Could you assign this issue to me? I am a beginner and this issue seems a good first issue to resolve.

**Comment by true1064** [comment]
done: https://github.com/cubefs/cubefs/pull/2353
