### ISSUE TITLE
卷创建报错，数据分片创建失败

### ISSUE THREAD

**Issue by fei922** [cubefs/cubefs#1533]
**Describe the bug**
创建卷报错，提示“action[createVol], clusterID[cubefs01] name:cfs-volume-1, err:action[createVol]  initDataPartitions failed, less than 3”
![image](https://user-images.githubusercontent.com/9672023/188785441-ac8d77f8-7e78-49b8-9900-3650db3b9a74.png)

master日志中显示两个datanode不可写，但是检查节点状态是没有问题的。为什么会这样，需要怎么解决？
![image](https://user-images.githubusercontent.com/9672023/188791313-dad5517f-7b27-40c4-a79b-a11d57651786.png)
![image](https://user-images.githubusercontent.com/9672023/188791496-d9e39014-603a-463e-b733-5896d1e34aba.png)

**Environment**
Describe your server system version, kernel version
CubeFS  Version : v3.0.0
OS : Ubuntu 20.04.4 LTS

root@master-1:~# cfs-cli cluster info 
[Cluster]
  Cluster name       : cubefs01
  Master leader      : 192.168.66.116:17010
  Auto allocate      : Enabled
  MetaNode count     : 3
  MetaNode used      : 0 GB
  MetaNode total     : 18 GB
  DataNode count     : 3
  DataNode used      : 16 GB
  DataNode total     : 569 GB
  Volume count       : 2
  EbsAddr            : 
  loadFactor         : 0
  BatchCount         : 0
  MarkDeleteRate     : 0
  DeleteWorkerSleepMs: 0
  AutoRepairRate     : 0

**Expected behavior**
预期卷创建成功，自动创建数据分片

**Comment by Victor1319** [comment]
@fei922 你是下线过datanode? 看你日志是datanode下线失败，一直处于待下线状态了，可以重启下master的leader节点就能恢复。另外看你只有3个节点，测试功能可能不太方便，建议保持4个节点用来测试验证

**Comment by fei922** [comment]
> @fei922 你是下线过datanode? 看你日志是datanode下线失败，一直处于待下线状态了，可以重启下master的leader节点就能恢复。另外看你只有3个节点，测试功能可能不太方便，建议保持4个节点用来测试验证

@Victor1319 重启了master的leader就好了，感谢解答。 建议咱们官方文档能多给出一些集群运维方面的指导，有时候遇到问题，没有相关资料，就无从下手了。
