### ISSUE TITLE
When I deploy the blobstore tinker, I get an error

### ISSUE THREAD

**Issue by craqShen** [cubefs/cubefs#1536]
**Describe the bug**
When I deploy the blobstore tinker, I get an error:
./tinker -f tinker.conf

2022/09/15 10:51:16.979858 [ERROR] common/config/load_conf.go:72 Parse conf failed: json: unknown field "database_conf"
2022/09/15 10:51:16.979907 [FATAL] cmd/cmd.go:107 init config error: json: unknown field "database_conf"

**Environment**
CentOS Linux release 7.9.2009 (Core)
3.10.0-1160.el7.x86_64

**To Reproduce**
Build according to the deployment document （https://cubefs.readthedocs.io/zh_CN/latest/user-guide/blobstore.html）and deploy in order.It seems that there is a problem with the json file format,but  nothing wrong with checking this json file

**Additional context**
#cat tinker.conf
{
   "bind_addr":":9700",
   "cluster_id":1,

   "database_conf":{
     "mongo":{
        "uri":"mongodb://10.0.4.121:27017"},
     "db_name":"tinker"},

   "shard_repair":{
        "broker_list":["10.0.4.121:9092"],
        "priority_topics":[
            {
                 "priority":1,
                 "topic":"shard_repair",
                 "partitions":[0]
            },
            {
                "priority":2,
                "topic":"shard_repair_prior",
                "partitions":[0]
             }
        ],
        "fail_topic":{
             "topic":"shard_repair_failed",
             "partitions":[0]
        }
   },
   "blob_delete":{
         "broker_list":["10.0.4.121:9092"],
         "normal_topic":{
             "topic":"blob_delete",
             "partitions":[0]
         },
         "fail_topic":{
             "topic":"fail_blob_delete",
             "partitions":[0]
         },
         "safe_delay_time_h":72,
         "dellog":{
             "dir":"./delete_log"
         }
   },
   "clustermgr":{
       "hosts":["http://10.0.4.121:9998","http://10.0.4.122:9999","http://10.0.4.123:10000"]
    },
   "scheduler":{
       "host":"http://10.0.4.122:9800"
   },
   "service_register":{
       "host":"http://10.0.4.122:9700",
       "idc":"z0"
   },
   "log":{
     "level":0,
     "filename":"/tmp/tinker.log"
   },
   "auditlog":{
     "logdir":"./auditlog/tinker"
   }
}

**Comment by pengtianyue025** [comment]
Sorry,  deployment document is a bit flawed, you can change "database_conf" to "database" and try again. we will update the document later.

**Comment by pengtianyue025** [comment]
the deployment document has been updated
