### ISSUE TITLE
cubefs本地无法编译通过，是否需要安装某些前置软件？

### ISSUE THREAD

**Issue by ptbxzrt** [cubefs/cubefs#1548]
您好！我尝试在自己wsl2的Ubuntu20.04上面编译部署cubefs，但根据文档的步骤进行编译始终报错无法通过
![image](https://user-images.githubusercontent.com/89020404/194591524-c66a4c20-e186-460a-9d05-733c44f0760a.png)
![image](https://user-images.githubusercontent.com/89020404/194591616-9c961755-bdb8-4da2-b52c-442d71643e9d.png)
请问是否是因为没有安装前置软件？或者对编译环境有特殊要求？谢谢！

**Comment by ptbxzrt** [comment]
另外，根据文档的步骤，另一个仓库里的blobstore、也就是纠删码子系统也无法编译。是对编译环境有什么要求，还是有什么重要的步骤没有写到文档上面。谢谢！！

**Comment by bboyCH4** [comment]
> 您好！我尝试在自己wsl2的Ubuntu20.04上面编译部署cubefs，但根据文档的步骤进行编译始终报错无法通过 ![image](https://user-images.githubusercontent.com/89020404/194591524-c66a4c20-e186-460a-9d05-733c44f0760a.png) ![image](https://user-images.githubusercontent.com/89020404/194591616-9c961755-bdb8-4da2-b52c-442d71643e9d.png) 请问是否是因为没有安装前置软件？或者对编译环境有特殊要求？谢谢！

您好，编译CubeFS有以下组件依赖（在centos7进行编译，供参考）
1. cmake 3.1版本以上。
2. go 1.16版本以上。
3. mvn。
4. bzip2-devel开发包。
这周我们会将这些信息同步在官网。

**Comment by ptbxzrt** [comment]
好的，谢谢解答！

**Comment by ptbxzrt** [comment]
部署blobstore的相关文档似乎也有问题，git链接不太对。部署相关的文档似乎都挺老了，如果可以的话，希望能够更新、完善一下。谢谢！

**Comment by sejust** [comment]
> 部署blobstore的相关文档似乎也有问题，git链接不太对。部署相关的文档似乎都挺老了，如果可以的话，希望能够更新、完善一下。谢谢！

您好，旧仓库（https://github.com/cubefs/cubefs-blobstore）即将废弃。

**Comment by sejust** [comment]
@ptbxzrt 您好，release-3.2.0 已经发布：https://github.com/cubefs/cubefs/releases/tag/v3.2.0

**Comment by ptbxzrt** [comment]
您好！似乎刚才发布了3.2版本，但现在又撤回了？

**Comment by sejust** [comment]
> 您好！似乎刚才发布了3.2版本，但现在又撤回了？

是的，我们整理以下版本信息，稍后发布。

**Comment by sejust** [comment]
https://github.com/cubefs/cubefs/releases/tag/v3.2.0  
3.2.0 版本以发布，欢迎试用。
