### ISSUE TITLE
Using bash to build blobstore all successed except cli 

### ISSUE THREAD

**Issue by hooklee2000** [cubefs/cubefs#1571]
**Describe the bug**
We Used bash to build blobstore.
 When downloading zlib printed 404 error.
Maybe we can modify build.sh file as such :
ZLIB_VER=1.2.13

Building blobstore all successed except cli , printed  erroer:
cubefs/blobstore/cli/cli outside available modules
make: *** [cli]

Finally we found using sh it all worked well.
**Environment**
3.2.0 in CentOS7

**Comment by sejust** [comment]
Thanks for your feedback, will fix it later.
