### ISSUE TITLE
Feature request: blobstore, auto build rpm

### ISSUE THREAD

**Issue by sejust** [cubefs/cubefs#1576]
build rpm

**Comment by 1996bzy** [comment]
Hello, could you please provide a step-by-step guide in the form of a README file on how to build RPM packages using the files you submitted?

**Comment by sejust** [comment]
> Hello, could you please provide a step-by-step guide in the form of a README file on how to build RPM packages using the files you submitted?

The RPM maker just build binary into package.  Pls build blobstore [like this](https://cubefs.io/zh/docs/master/user-guide/blobstore.html#%E7%BC%96%E8%AF%91%E6%9E%84%E5%BB%BA), then config and auto start with supervisor or other tools.

**Comment by 1996bzy** [comment]
I am trying to build an RPM package for the blobstore using the files you provided, but I am encountering the following issues: If I run "make build_rpm" in the /cubefs/blobstore directory, I get an error saying "go.mod file not found," and if I run it in the /cubefs directory, I get an error saying "No rule to make target."

**Comment by 1996bzy** [comment]
So I was wondering, how can I automatically build the blobstore RPB package using the `make build_rpm` command?
