### ISSUE TITLE
read the file failed, report  extent error

### ISSUE THREAD

**Issue by bboyCH4** [cubefs/cubefs#1596]
**Describe the bug**
read the file failed
![image](https://user-images.githubusercontent.com/19317218/199881361-0c1e109c-55ed-402b-8e7f-9e9ba2b806a4.png)

**Additional context**
check the error log on data,it shows the extent had been deleted。
![image](https://user-images.githubusercontent.com/19317218/199881243-fa3e683d-7eb6-4357-b25c-b7e7327e3d18.png)

**Comment by true1064** [comment]
@bboyCH4 confiremed this is fixed
