### ISSUE TITLE
Complete an independent and third party security

### ISSUE THREAD

**Issue by pengtianyue025** [cubefs/cubefs#1654]
Have completed an independent and third party security audit with results published of similar scope and quality as the following example (including critical vulnerabilities addressed): https://github.com/envoyproxy/envoy#security-audit and all critical vulnerabilities need to be addressed before graduation.

refer to
1. CNCF Graduation Criteria：https://github.com/cncf/toc/blob/main/process/graduation_criteria.md

**Comment by leonrayang** [comment]
CubeFS was accepted to CNCF on December 16, 2019, moved to the Incubating maturity level on July 3, 2022, and then moved to the Graduated maturity level on December 11, 2024.

https://www.cncf.io/projects/cubefs/
