### ISSUE TITLE
[Docs] 对象存储部分的文档有个插图出现小错误

### ISSUE THREAD

**Issue by lizonglingo** [cubefs/cubefs#1663]
图片链接：
- 中文文档：https://github.com/cubefs/cubefs/blob/master/docs-zh/source/pic/cfs-object-subsystem-semantic.png
- 英文文档：https://github.com/cubefs/cubefs/blob/master/docs/source/pic/cfs-object-subsystem-semantic.png

问题：
![image](https://user-images.githubusercontent.com/40293922/218528428-295a1550-0568-4e59-92b8-3b1c764990cf.png)
箭头位置的 目录结构 和 说明 没有对应。

**Comment by xiaochunhe** [comment]
thank you，we'll fix it later
