### ISSUE TITLE
Update CNCF Landcape Summary Table with CubeFS details

### ISSUE THREAD

**Issue by siforster** [cubefs/cubefs#1667]
Hi All,

The CNCF Business Value Subcommittee has developed a project summary table to supplement the CNCF Landscape and include further information about CNCF projects for the wider cloud native community. We would like to request the CubeFS project submit a PR to the CNCF Landscape repository with additional details that will help further inform the community about your project and its use cases through the popular landscape and this new addition.

The table is located here: https://landscape.cncf.io/summary
There are directions located here: https://github.com/cncf/landscape/blob/master/readme_summary.md

Many thanks for this - we hope it will help further get the word out about CubeFS!

Simon Forster
CNCF Business Value Subcomittee

**Comment by xiaochunhe** [comment]
Thank you，we will move this forward

**Comment by siforster** [comment]
Thank you so much!

**Comment by pengtianyue025** [comment]
Hi Simon, 

I have initiated a pull request, please review (https://github.com/cncf/landscape/pull/3049).

Thank you so much!

**Comment by siforster** [comment]
Hi @pengtianyue025

Thank you very much for doing thisl - the content is definitely helpful for the community.
I see that it has failed the DCO check - may I ask if you could correctly sign the commit?
There are directions included in the check:
https://github.com/cncf/landscape/pull/3049/checks?check_run_id=11385540642

Many thanks,

Simon

**Comment by pengtianyue025** [comment]
Hi Simon,

I just fixed this， please check again.

Thanks again

Tianyue

**Comment by siforster** [comment]
Thanks @pengtianyue025 - I see this has been merged; thank you for doing this!
