### ISSUE TITLE
[Feature]: Create SECURITY.md

### ISSUE THREAD

**Issue by caniszczyk** [cubefs/cubefs#1735]
https://github.com/cubefs/cubefs/tree/master/security is a great place

However, GitHub expects a SECURITY.md at the root of the repo

https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository

This is a very simple fix :)

**Comment by xiaochunhe** [comment]
yes，we create it : https://github.com/cubefs/cubefs/blob/master/SECURITY.md
