### ISSUE TITLE
[Bug]: cfs-cli build fatal error

### ISSUE THREAD

**Issue by wangshli** [cubefs/cubefs#1847]
**Describe the bug**
cfs-cli build error
<img width="607" alt="微信图片_20230322161149" src="https://user-images.githubusercontent.com/89928606/226839627-7fdbaa52-8678-467f-85a6-61c242e74879.png">

**Environment**
CentOS Linux release 8.5.2111
Linux version 4.18.0-348.el8.x86_64 

**Expected behavior**
cfs-cli build success

**Additional context**

**Comment by leonrayang** [comment]
please use ”make cli“ at your root of source code dir. The issue is accepted
