### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by vccomnet** [cubefs/cubefs#1886]
**Describe the bug**
单机版方式运行，创建卷指定size 为10G，各个服务状态正常，但是卷无法写入数据

**Environment**
Centos 7 X86_64 , VM ware 虚拟机，虚拟机内存8G， 磁盘100G

**To Reproduce**
必现，操作步骤如下
1. sh shell/depoly.sh /data ens33
2. ./cfs-cli volume create abc abc --size 10
3. 修改/data/conf/client.conf 中的volName 和 owner 为 abc
4. ./cfs-client -c /data/conf/client.conf
5. cp cfs-cli /data/client/mnt/  复制文件到卷中，发生错误：
cp: error writing“/data/client/mnt/cfs-cli': Input/output error
cp: failed to extend"/data/client/mnt/cfs-cli': Input/output error
cp: failed to close "/data/client/mnt/cfs-cli':Input/output error

**Expected behavior**
正常应该无任何提示，文件被复制到卷中

**Additional context**
Victor 已经定位到问题，在创建卷时，不指定 --size ，则无此问题。

**Comment by Victor1319** [comment]
`--size int                  Specify data partition size[Unit: GB] (default 120)`， you should user `--capacity 10`, data partition size will be rdonly once size less than 10G， so it will be input/output error.
