### ISSUE TITLE
[Bug]: 本地编译后的二进制程序无法在其他机器上执行

### ISSUE THREAD

**Issue by htlin65535** [cubefs/cubefs#1891]
**Describe the bug**
centos7 本地编译后的 cfs-server 无法在其他机器上执行，报错信息
[root@cube01 tmp]# ./cfs-server --help
Illegal instruction

**Environment**
编译环境：
kernel：5.16.12-1.el7.elrepo.x86_64
bzip2-devel-1.0.6-13.el7.x86_64
gcc-c++-4.8.5-44.el7.x86_64
cmake3-data-3.17.5-1.el7.noarch
cmake3-3.17.5-1.el7.x86_64
go version go1.20.1 linux/amd64

**Comment by htlin65535** [comment]
已经解决了

**Comment by sworduo** [comment]
我也遇到了这个问题，请问大佬是怎么解决的。
