### ISSUE TITLE
[Feature]: The cfs-cli tool displays nodeset information

### ISSUE THREAD

**Issue by pengtianyue025** [cubefs/cubefs#1894]
**Describe the solution you'd like**
- Realize the display of information such as nodeset, and realize the display of dp and mp across nodeset
- Cross-nodeset dp, mp metrics reporting and cli display
- The total amount of nodeset, space, etc.

**Additional context**
nodeset is used as a fault domain unit, and the information is not displayed on the cli side.

**Comment by NaturalSelect** [comment]
Hello, I am interested in this topic and have written application for it.

**Comment by zmc-x** [comment]
> Hello, I am interested in this topic and I have written application for it.

This topic is a ospp project. If you want to take part in this topic，you might to apply this project in the ospp website. Although the cubefs  is open source project.

**Comment by JasonHu520** [comment]
@true1064 Check out this PR

**Comment by true1064** [comment]
> @true1064 Check out this PR

checking
