### ISSUE TITLE
[Feature]: The cfs-cli displays disk information of DataNode

### ISSUE THREAD

**Issue by pengtianyue025** [cubefs/cubefs#1895]
**Describe the solution you'd like**
The following information needs to be displayed: 
- Missing dp situation (lack partitions)
- dp quantity, extent situation
- Space usage, load

**Additional context**
At present, the bad disk information will be reported and displayed through metrics, but there is no usage display of the disk dimension on the cli side.

**Comment by morphes1995** [comment]
Is this problem still exists and need to be resolved ?
