### ISSUE TITLE
[Feature]: Don't use global variable when implementing `maxDpCntLimit` func

### ISSUE THREAD

**Issue by pengtianyue025** [cubefs/cubefs#1897]
**Describe the solution you'd like**
remove global variable `maxDpCntOneNode`

**Additional context**
In order to avoid too many dp on each datanode node, the limit is increased. The default is 3000. If the limit is exceeded, no more dp can be created. Currently, query updates through the interface are supported.
curl -v "http://192.168.0.11:17010/admin/getNodeInfo"
curl -v "http://192.168.0.11:17010/admin/setNodeInfo?maxDpCntLimit=xxx"

**Comment by pengtianyue025** [comment]
> If you mean a global setting for the maximum number of dp on datanode, then it could work!
> 
> ```
> $ go test --run TestSetNodeMaxDpCntLimit
> 
> 200
> {"code":0,"msg":"success","data":"set nodeinfo params map[maxDpCntLimit:4000] successfully"}
> 200
> {"code":0,"msg":"success","data":{"autoRepairRate":"0","batchCount":"0","deleteWorkerSleepMs":"0","loadFactor":"100","markDeleteRate":"0","maxDpCntLimit":"4000"}}
> 200
> {"code":0,"msg":"success","data":{"TotalWeight":1099511627776,"UsedWeight":5368709120,"AvailableSpace":1099511627776,"ID":2,"Zone":"zone1","Addr":"127.0.0.1:9101","DomainAddr":"localhost:9101,kubernetes.docker.internal:9101","ReportTime":"2023-04-28T03:23:38.633730617+08:00","IsActive":true,"IsWriteAble":true,"UsageRatio":0.0048828125,"SelectedTimes":0,"Carry":0.7236733671193932,"DataPartitionReports":[],"DataPartitionCount":3,"NodeSetID":1,"PersistenceDataPartitions":[],"BadDisks":null,"RdOnly":false,"maxDpCntLimit":4000}}
> PASS
> ok      github.com/cubefs/cubefs/master 15.818s
> ```
> 
> My simple unit code test is follows:
> 
> ```go
> func TestSetNodeMaxDpCntLimit(t *testing.T) {
> 	// change current max data partition count limit to 4000
> 	limit := uint32(4000)
> 	reqURL := fmt.Sprintf("%v%v?maxDpCntLimit=%v", hostAddr, proto.AdminSetNodeInfo, limit)
> 	process(reqURL, t)
> 	// query current settings
> 	reqURL = fmt.Sprintf("%v%v", hostAddr, proto.AdminGetNodeInfo)
> 	reply := process(reqURL, t)
> 	data := reply.Data.(map[string]interface{})
> 	limitStr := (data[maxDpCntLimitKey]).(string)
> 	assert.True(t, fmt.Sprint(limit) == limitStr)
> 	// query data node info
> 	reqURL = fmt.Sprintf("%v%v?addr=%v", hostAddr, proto.GetDataNode, mds1Addr)
> 	reply = process(reqURL, t)
> 	data = reply.Data.(map[string]interface{})
> 	dataNodeLimit := uint32((data[maxDpCntLimitKey]).(float64))
> 	assert.True(t, dataNodeLimit == limit)
> }
> ```
> 
> @pengtianyue025 Looking forward for your reply, if so I will open a pull request.

Thank you for your submission. You were quick to respond. Victor @Victor1319  will review this task, and we will get back to you later.

**Comment by NaturalSelect** [comment]
> > If you mean a global setting for the maximum number of dp on datanode, then it could work!
> > ```
> > $ go test --run TestSetNodeMaxDpCntLimit
> > 
> > 200
> > {"code":0,"msg":"success","data":"set nodeinfo params map[maxDpCntLimit:4000] successfully"}
> > 200
> > {"code":0,"msg":"success","data":{"autoRepairRate":"0","batchCount":"0","deleteWorkerSleepMs":"0","loadFactor":"100","markDeleteRate":"0","maxDpCntLimit":"4000"}}
> > 200
> > {"code":0,"msg":"success","data":{"TotalWeight":1099511627776,"UsedWeight":5368709120,"AvailableSpace":1099511627776,"ID":2,"Zone":"zone1","Addr":"127.0.0.1:9101","DomainAddr":"localhost:9101,kubernetes.docker.internal:9101","ReportTime":"2023-04-28T03:23:38.633730617+08:00","IsActive":true,"IsWriteAble":true,"UsageRatio":0.0048828125,"SelectedTimes":0,"Carry":0.7236733671193932,"DataPartitionReports":[],"DataPartitionCount":3,"NodeSetID":1,"PersistenceDataPartitions":[],"BadDisks":null,"RdOnly":false,"maxDpCntLimit":4000}}
> > PASS
> > ok      github.com/cubefs/cubefs/master 15.818s
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > My simple unit code test is follows:
> > ```go
> > func TestSetNodeMaxDpCntLimit(t *testing.T) {
> > 	// change current max data partition count limit to 4000
> > 	limit := uint32(4000)
> > 	reqURL := fmt.Sprintf("%v%v?maxDpCntLimit=%v", hostAddr, proto.AdminSetNodeInfo, limit)
> > 	process(reqURL, t)
> > 	// query current settings
> > 	reqURL = fmt.Sprintf("%v%v", hostAddr, proto.AdminGetNodeInfo)
> > 	reply := process(reqURL, t)
> > 	data := reply.Data.(map[string]interface{})
> > 	limitStr := (data[maxDpCntLimitKey]).(string)
> > 	assert.True(t, fmt.Sprint(limit) == limitStr)
> > 	// query data node info
> > 	reqURL = fmt.Sprintf("%v%v?addr=%v", hostAddr, proto.GetDataNode, mds1Addr)
> > 	reply = process(reqURL, t)
> > 	data = reply.Data.(map[string]interface{})
> > 	dataNodeLimit := uint32((data[maxDpCntLimitKey]).(float64))
> > 	assert.True(t, dataNodeLimit == limit)
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > @pengtianyue025 Looking forward for your reply, if so I will open a pull request.
> 
> Thank you for your submission. You were quick to respond. Victor @Victor1319 will review this task, and we will get back to you later.

Thank you.

**Comment by pengtianyue025** [comment]
@Victor1319

**Comment by Victor1319** [comment]
`Need to support configuration through cli, and can view`
@NaturalSelect what you should do is to update code of cfs-cli to support update `maxDpCntLimit` by cfs-cli.

**Comment by NaturalSelect** [comment]
> `Need to support configuration through cli, and can view` @NaturalSelect what you should do is to update code of cfs-cli to support update by cfs-cli.`maxDpCntLimit`

Ok, I will complete it later.

Thank you.

**Comment by NaturalSelect** [comment]
It's confusing, the code already exists in the previous code, it just doesn't work.
```go
func newClusterSetParasCmd(client *master.MasterClient) *cobra.Command {
	var optAutoRepairRate, optMarkDeleteRate, optDelBatchCount, optDelWorkerSleepMs, optLoadFactor, opMaxDpCntLimit string
	var cmd = &cobra.Command{
		Use:   CliOpSetCluster,
		Short: cmdClusterSetClusterInfoShort,
		Run: func(cmd *cobra.Command, args []string) {
			var (
				err error
			)
			defer func() {
				if err != nil {
					errout("Error: %v", err)
				}
			}()

			if err = client.AdminAPI().SetClusterParas(optDelBatchCount, optMarkDeleteRate, optDelWorkerSleepMs, optAutoRepairRate, optLoadFactor, opMaxDpCntLimit); err != nil {
				return
			}
			stdout("Cluster parameters has been set successfully. \n")
		},
	}
	cmd.Flags().StringVar(&optDelBatchCount, CliFlagDelBatchCount, "", "MetaNode delete batch count")
	cmd.Flags().StringVar(&optLoadFactor, CliFlagLoadFactor, "", "Load Factor")
	cmd.Flags().StringVar(&optMarkDeleteRate, CliFlagMarkDelRate, "", "DataNode batch mark delete limit rate. if 0 for no infinity limit")
	cmd.Flags().StringVar(&optAutoRepairRate, CliFlagAutoRepairRate, "", "DataNode auto repair rate")
	cmd.Flags().StringVar(&optDelWorkerSleepMs, CliFlagDelWorkerSleepMs, "", "MetaNode delete worker sleep time with millisecond. if 0 for no sleep")
	cmd.Flags().StringVar(&opMaxDpCntLimit, CliFlagMaxDpCntLimit, "", "Maximum number of dp on each datanode, default 3000, 0 represents setting to default")

	return cmd
}
```
And the output of cli as so:

```log
./cfs-cli cluster set -h
Set cluster parameters

Usage:
  cfs-cli cluster set [flags]

Flags:
      --autoRepairRate string        DataNode auto repair rate
      --batchCount string            MetaNode delete batch count
      --deleteWorkerSleepMs string   MetaNode delete worker sleep time with millisecond. if 0 for no sleep
  -h, --help                         help for set
      --loadFactor string            Load Factor
      --markDeleteRate string        DataNode batch mark delete limit rate. if 0 for no infinity limit
      --maxDpCntLimit string         Maximum number of dp on each datanode, default 3000, 0 represents setting to default
```
