### ISSUE TITLE
[Feature]: The blobstore-cli supports setting background task switch

### ISSUE THREAD

**Issue by pengtianyue025** [cubefs/cubefs#1898]
**Describe the solution you'd like**
- The blobstore-cli tool supports querying switch status
- The blobstore-cli tool supports enabling or disabling the background task switch

**Additional context**
The background tasks of blobstore include `disk_repair`, `balance`, `disk_drop`, `volume_inspect`, `shard_repair`, and `blob_delete`. The task switches are stored in Clustermgr. You can set the switch by requesting the "/config/set" interface of Clustermgr, and query through "/config/get" Switch status, for more convenient setting or query, we need to integrate it into the cli tool.

**Comment by cloorc** [comment]
@pengtianyue025 Hi, it's a little weird that `slice#Exists` doesn't exist, would you please have a look?

```golang
/* table function list */
func (t *table) Get(key []byte, opts ...OpOption) (data []byte, err error) {
	cValue, err := t.db.GetCF(t.ro, t.cf, key)
	if err != nil {
		return nil, err
	}
	defer cValue.Free()

	if !cValue.Exists() { // **HERE is the error**
		err = ErrNotFound
		return
	}
        // ....
}
```

![image](https://user-images.githubusercontent.com/13597105/235829751-dd587088-5b0b-489d-a395-4ca9a6a17f1d.png)

**Comment by cloorc** [comment]
> @pengtianyue025 Hi, it's a little weird that `slice#Exists` doesn't exist, would you please have a look?
> 
> In file `blobstore/common/kvstore/table.go`
> 
> ```go
> /* table function list */
> func (t *table) Get(key []byte, opts ...OpOption) (data []byte, err error) {
> 	cValue, err := t.db.GetCF(t.ro, t.cf, key)
> 	if err != nil {
> 		return nil, err
> 	}
> 	defer cValue.Free()
> 
> 	if !cValue.Exists() { // **HERE is the error**
> 		err = ErrNotFound
> 		return
> 	}
>         // ....
> }
> ```
> 
> ![image](https://user-images.githubusercontent.com/13597105/235829751-dd587088-5b0b-489d-a395-4ca9a6a17f1d.png)

It seems like the parent `go.mod` replaced a wrong version:

```
	github.com/tecbot/gorocksdb => github.com/tecbot/gorocksdb v0.0.0-20171109104638-15d543158317
```

I just comment out this line and everything works fine now.
