### ISSUE TITLE
[Feature]: The blobstore-cli supports Clustermgr to switch masters

### ISSUE THREAD

**Issue by pengtianyue025** [cubefs/cubefs#1901]
**Describe the solution you'd like**
- blobstore-cli supports switching masters to specified nodes
- blobstore-cli supports viewing node master-slave information

**Additional context**
When upgrading the Clustermgr service, it is also necessary to ensure the normal access of the business. You need to upgrade the slave nodes first, wait for all the slave nodes to be upgraded, switch the master node to a slave node that has been upgraded, and finally upgrade the old master node. During the entire upgrade process, in order to ensure that there is always a master node to provide services, a manual master cut operation is required.

**Comment by sjcsjc123** [comment]
I would like to ask if the `cm stat` command and `cm cluster transfer` command have already implemented this issue.
First, i execute the `cm stat` command.
![image](https://github.com/cubefs/cubefs/assets/88550136/1bcdb88b-2a22-4933-b1fe-6b7607f29bed)
Then, i execute the `cm cluster transfer 3` command.
![image](https://github.com/cubefs/cubefs/assets/88550136/b5573d0e-6649-4dd0-bd0a-ba15b13c32ef)
i find the leader host has already changed.

**Comment by sjcsjc123** [comment]
Or can I simplify the information displayed by the `cm stat` function?

**Comment by sjcsjc123** [comment]
@xiangcai1215  @pengtianyue025

**Comment by xiangcai1215** [comment]
> Or can I simplify the information displayed by the `cm stat` function and copy it into Access?

Yes，This feature has already been implemented in cli  and no need copy it into Access. 
Can you choose another one.
