### ISSUE TITLE
[Feature]: The RPC module of the erasure code system supports downloading crc data integrity verification

### ISSUE THREAD

**Issue by pengtianyue025** [cubefs/cubefs#1914]
**Describe the solution you'd like**
- Support the integrity guarantee of data downlink; is there a more optimized solution than the current upload verification?

**Additional context**
The current rpc of CubeFS only uploads data integrity checks

**Comment by fengshunli** [comment]
assign to me

**Comment by sejust** [comment]
The issue has some incompleteness and is closed for now.
