### ISSUE TITLE
[Feature]: Master does snapshot optimization

### ISSUE THREAD

**Issue by pengtianyue025** [cubefs/cubefs#1916]
**Describe the solution you'd like**
- Consider cleaning up the rocksdb solution and make some optimizations, such as dropping the entire rocksdb and reinitializing.

**Additional context**
The current master's follower needs to clean up the rocksdb before accepting the leader's snapshot to prevent the information that has expired on the leader from being retained.

**Comment by NaturalSelect** [comment]
Hello.

I describe my solution here：
* First we close current rocksdb instance to stop other persistent request.
* Second we use `os.TempDir` to create a temporary rocksdb instance.
* Third we use `BatchPut()` put all key value pairs of snapshot to temporary rocksdb instance.
* Fourth we close temporary rocksdb instance, and use atomic posix `rename()` move the directory of  temporary rocksdb instance to our real rocksdb directory.
* Finally we reopen the rocksdb instance.

Could you help me check my solution?

**Comment by leonrayang** [comment]
@NaturalSelect 

> Hello, @wuchunhuan.
> 
> I describe my solution here：
> 
> 1. Close current rocksdb instance to stop other persistent request.
> 2. Use `db.dir + "_temp"` to create a temporary rocksdb instance.
> 3. Use `BatchPut()` put all key value pairs of snapshot to temporary rocksdb instance.
> 4. Close temporary rocksdb instance, and use atomic `rename()` move the directory of  temporary rocksdb instance to our real rocksdb directory.
> 5. Reopen the rocksdb instance.
> 
> The benchmark code:
> 
> ```go
> const volForSnapshot = "snapshtVol"
> 
> const volForSnapshotCount = 300
> 
> func BenchmarkSnapshot(b *testing.B) {
> 	var err error
> 	// perpare status
> 	req := &createVolReq{
> 		name:             "",
> 		owner:            "cfs",
> 		size:             1,
> 		mpCount:          1,
> 		dpReplicaNum:     3,
> 		capacity:         300,
> 		followerRead:     false,
> 		authenticate:     false,
> 		crossZone:        false,
> 		normalZonesFirst: false,
> 		zoneName:         testZone2,
> 		description:      "",
> 		qosLimitArgs:     &qosArgs{},
> 	}
> 	for i := 0; i != volForSnapshotCount; i++ {
> 		req.name = fmt.Sprintf("%v_%v", volForSnapshot, i)
> 		server.cluster.createVol(req)
> 	}
> 	time.Sleep(5 * time.Second)
> 	mdSnapshot, err := server.cluster.fsm.Snapshot()
> 	if err != nil {
> 		b.Error(err)
> 		return
> 	}
> 	b.Logf("snapshot apply index[%v]\n", mdSnapshot.ApplyIndex())
> 	s := &Server{}
> 
> 	var dbStore *raftstore.RocksDBStore
> 	dbStore, err = raftstore.NewRocksDBStore("/tmp/cubefs/raft3", LRUCacheSize, WriteBufferSize)
> 	if err != nil {
> 		b.Fatalf("init rocks db store fail cause: %v", err)
> 	}
> 	defer dbStore.Close()
> 	fsm := &MetadataFsm{
> 		rs:    server.fsm.rs,
> 		store: dbStore,
> 	}
> 	fsm.registerApplySnapshotHandler(func() {
> 		fsm.restore()
> 	})
> 	s.fsm = fsm
> 	peers := make([]rproto.Peer, 0, len(server.config.peers))
> 	for _, peer := range server.config.peers {
> 		peers = append(peers, peer.Peer)
> 	}
> 	b.StopTimer()
> 	b.ResetTimer()
> 	b.StartTimer()
> 	if err = fsm.ApplySnapshot(peers, mdSnapshot); err != nil {
> 		b.Error(err)
> 		return
> 	}
> 	b.StopTimer()
> 	if fsm.applied != mdSnapshot.ApplyIndex() {
> 		b.Errorf("applied not equal,applied[%v],snapshot applied[%v]\n", fsm.applied, mdSnapshot.ApplyIndex())
> 		return
> 	}
> 	mdSnapshot.Close()
> }
> ```
> 
> The benchmark create **300** volumes to simulate a big status, it make `appiled index` increase to **17517**.
> 
> Before:
> 
> ```
> 1000000000	         0.2425 ns/op	       0 B/op	       0 allocs/op
> --- BENCH: BenchmarkSnapshot-12
>     master_manager_test.go:97: snapshot apply index[17517]
>     master_manager_test.go:97: snapshot apply index[17517]
>     master_manager_test.go:97: snapshot apply index[17517]
>     master_manager_test.go:97: snapshot apply index[17517]
>     master_manager_test.go:97: snapshot apply index[17517]
>     master_manager_test.go:97: snapshot apply index[17517]
>     master_manager_test.go:97: snapshot apply index[17517]
>     master_manager_test.go:97: snapshot apply index[17517]
>     master_manager_test.go:97: snapshot apply index[17517]
>     master_manager_test.go:97: snapshot apply index[17517]
> 	... [output truncated]
> PASS
> ```
> 
> The full log could be found in [here](https://github.com/NaturalSelect/logs/blob/main/bench_before.log).
> 
> After:
> 
> ```
> 1000000000	         0.1297 ns/op	       0 B/op	       0 allocs/op
> --- BENCH: BenchmarkSnapshot-12
>     master_manager_test.go:97: snapshot apply index[17517]
>     master_manager_test.go:97: snapshot apply index[17517]
>     master_manager_test.go:97: snapshot apply index[17517]
>     master_manager_test.go:97: snapshot apply index[17517]
>     master_manager_test.go:97: snapshot apply index[17517]
>     master_manager_test.go:97: snapshot apply index[17517]
>     master_manager_test.go:97: snapshot apply index[17517]
>     master_manager_test.go:97: snapshot apply index[17517]
>     master_manager_test.go:97: snapshot apply index[17517]
>     master_manager_test.go:97: snapshot apply index[17517]
> 	... [output truncated]
> PASS
> ```
> 
> The full log could be found in [here](https://github.com/NaturalSelect/logs/blob/main/bench_after.log).
> 
> Please assign this issue to me, and I will open a pull request for it.
> 
> _NOTE: this scheme has bad performance when the status is small._
> 
> My changes could be found in [here](https://github.com/NaturalSelect/cubefs/commit/c662e2dbdddcbbefc4d69d6ca1660855c6117fb7).

LGTM

**Comment by NaturalSelect** [comment]
Hello @leonrayang.

I have open a [pull request](https://github.com/cubefs/cubefs/pull/2124) for it, waiting for your review.

**Comment by true1064** [comment]
done: https://github.com/cubefs/cubefs/pull/2124
