### ISSUE TITLE
[Feature]: Master/DataNode/MetaNode start log optimization

### ISSUE THREAD

**Issue by pengtianyue025** [cubefs/cubefs#1917]
**Describe the solution you'd like**
- Print the error log in the startup process to the output.

**Additional context**
Currently, each role (In addition to erasure code system) has an output log and role name _error.log. During the startup process, not all of them are printed to the output log, but some are in the role name _error.log. The role name _error.log has a relatively large amount of data, and it is not easy to analyze the cause of the startup failure.

**Comment by Chever-John** [comment]
Hi, is this issue still ongoing. @leonrayang 
Can I continue with the work? @pengtianyue025

**Comment by baijiaruo** [comment]
> Hi, is this issue still ongoing. @leonrayang Can I continue with the work? @pengtianyue025

yes， you can keep doing

**Comment by true1064** [comment]
done: https://github.com/cubefs/cubefs/pull/2350
