### ISSUE TITLE
[Feature]: Master qosClientId allocation optimization

### ISSUE THREAD

**Issue by pengtianyue025** [cubefs/cubefs#1918]
**Describe the solution you'd like**
- It can be optimized to allocate a batch of id numbers at a time, such as 100, so that multiple requests can be persisted at one time, reducing raft and disk pressure.

**Additional context**
At present, when each client starts, it will apply for a clientId (self-increasing unique id) from the master for qos flow control, and the id will be persisted to rocksdb through raft every time it is applied. If there are multiple new client mount requests frequently, it will cause the raft log to grow too fast, and because it needs to be applied to the disk, there is a requirement for disk performance.

**Comment by NaturalSelect** [comment]
I have a scheme that doesn't require raft to persist data.

Just split `clientId` to two parts `|raft term|self-increasing unique| `, each part is 32 bits, and then `clientId` could be allocated in single master node.

**Comment by Victor1319** [comment]
good idea!

**Comment by NaturalSelect** [comment]
> good idea!

Please assign #1918 to me, and I will open a pull request for it.

**Comment by NaturalSelect** [comment]
Hello @Victor1319.

I have open a [pull request](https://github.com/cubefs/cubefs/pull/2112) for it, waiting for your review.
