### ISSUE TITLE
[Feature]: Optimize RPC Audit Log Filtering Rules

### ISSUE THREAD

**Issue by JasonHu520** [cubefs/cubefs#1924]
**Backround:**
The audit log is a key basic component of each project and fully records the entire process of each request. However, in high-concurrency HTTP services, too many detailed audit logs will bring some problems, such as reducing service performance, occupying storage capacity, and wasting log indexing services. So a set of rules is needed to filter useful audit logs.
high-quality code, tests, and documentation
**Requirement**：
audit log is a kind of structured data, maybe the [Query DSL design of ES](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl.html) will provide some help,  filter performance require in nanoseconds

**Comment by shouao** [comment]
Hi, I am very interested in this feature and I will submit my application report before the deadline.

**Comment by JasonHu520** [comment]
@shouao How is the progress, welcome to come here to discuss together

> 

Hi，How is the progress?  welcome to come here to discuss together

**Comment by JasonHu520** [comment]
> Hi, guys I am very interested in this feature, I have internship experience in the infrastructure team of a tech company. I will apply for this task at OSPP and submit a feature report before the deadline of OSPP.

Hi, How is the progress? welcome to come here to discuss together

**Comment by sejust** [comment]
done
