### ISSUE TITLE
[Feature]: Optimize CubeFS containerized deployments

### ISSUE THREAD

**Issue by baijiaruo** [cubefs/cubefs#1927]
### Description of Requirement
- The current CubeFS containerized deployment uses a bash script, which has a single function and only supports one-click deployment and cleanup. It does not support cluster topology modification, single service/role upgrade, one-click upgrade and expansion, cluster operation and maintenance management, etc.
 - The project needs to use the Go language for containerized deployment reconstruction, supports containerized deployment of clusters based on topology files, and supports functions such as one-click upgrade and expansion.
### Project Output Requirements
- Functional documentation of the deployment tool, including functions such as one-click deployment, cleaning, capacity expansion, and upgrade
- According to the documentation, the implementation of the deployment tool code is completed, and the functional verification basically passes

**Comment by PTTQ** [comment]
你好，我准备申请这个项目

**Comment by aFlyBird0** [comment]
Hello, I'm interested in this project and have already started contributing to the CubeFS community. I have sent my resume to your oppo email. Thank you! @baijiaruo

**Comment by ytyuanxi** [comment]
Verification of Container Deployment Scheme Using Docker's Host Network Pattern

- cluster

![image](https://github.com/cubefs/cubefs/assets/30840540/71dc9983-6507-49ae-a56a-e42ef14bf43c)


- datanode

<img width="669" alt="1d2d0695ee6eb0f87d5424f7bfb788d" src="https://github.com/cubefs/cubefs/assets/30840540/dfe716fc-e6df-4471-af85-5059174f882e">

<img width="671" alt="e4780e64dc10ffc04d15d15ef6b72dc" src="https://github.com/cubefs/cubefs/assets/30840540/6624756a-284b-431a-b656-8086b541c443">

- metanode

<img width="641" alt="c1aae5fd1fb0e8ed03bd2d28aa3c479" src="https://github.com/cubefs/cubefs/assets/30840540/44aaa61e-fc22-48c3-923d-a1d7eda7466f">

- volume

<img width="586" alt="ecc0f22ba5d2fc2938ae5bb6d1fc826" src="https://github.com/cubefs/cubefs/assets/30840540/5c2ee57f-8a79-447a-b364-3e27adf492d3">
<img width="763" alt="398f33e06c4b4f8e73e17b2bb961564" src="https://github.com/cubefs/cubefs/assets/30840540/41048a6f-58f4-47c7-9bb8-f07db640b9b1">
<img width="752" alt="be686805938b28f42427707d599cfc2" src="https://github.com/cubefs/cubefs/assets/30840540/a5b109ef-e46a-44b9-8b5c-cba93c2440ea">

**Comment by baijiaruo** [comment]
This is just a rendering after deployment，but some specific deployment steps have not been seen，At the same time, I hope to see further detailed design plans after prototype verification @ytyuanxi

**Comment by ytyuanxi** [comment]
specific deployment steps：

A total of three virtual machines, each to deploy master, datanode, metanode

- master

``` 
docker run -d --name master1  -v /date/disk/master1/data:/cfs/data -v /home/yxt/cubefs/build/bin:/cfs/bin:ro -v /data/disk/master1/log:/cfs/log -v /home/yxt/cubefs/docker/conf/master1.json:/cfs/conf/master.json -v /home/yxt/cubefs/docker/script/start_master.sh:/cfs/script/start.sh --restart on-failure --privileged     --network  host   docker.io/cubefs/cbfs-base:1.0-golang-1.17.13 /bin/sh /cfs/script/start.sh

docker run -d --name master2  -v /date/disk/master2/data:/cfs/data -v /home/yxt/cubefs/build/bin:/cfs/bin:ro -v /data/disk/master2/log:/cfs/log -v /home/yxt/cubefs/docker/conf/master2.json:/cfs/conf/master.json -v /home/yxt/cubefs/docker/script/start_master.sh:/cfs/script/start.sh --restart on-failure --privileged     --network  host   docker.io/cubefs/cbfs-base:1.0-golang-1.17.13 /bin/sh /cfs/script/start.sh

docker run -d --name master3  -v /date/disk/master3/data:/cfs/data -v /home/yxt/cubefs/build/bin:/cfs/bin:ro -v /data/disk/master3/log:/cfs/log -v /home/yxt/cubefs/docker/conf/master3.json:/cfs/conf/master.json -v /home/yxt/cubefs/docker/script/start_master.sh:/cfs/script/start.sh --restart on-failure --privileged      --network  host   docker.io/cubefs/cbfs-base:1.0-golang-1.17.13 /bin/sh /cfs/script/start.sh
 ```


- metanode

```
docker run -d --name metanode1  -v /date/disk/metanode1/data:/cfs/data -v /home/yxt/cubefs/build/bin:/cfs/bin:ro -v /data/disk/metanode1/log:/cfs/log -v /home/yxt/cubefs/docker/conf/metanode.json:/cfs/conf/metanode.json -v /home/yxt/cubefs/docker/script/start_meta.sh:/cfs/script/start.sh --restart on-failure --privileged     --network  host   docker.io/cubefs/cbfs-base:1.0-golang-1.17.13 /bin/sh /cfs/script/start.sh


docker run -d --name metanode2 -v /date/disk/metanode2/data:/cfs/data -v /home/yxt/cubefs/build/bin:/cfs/bin:ro -v /data/disk/metanode2/log:/cfs/log -v /home/yxt/cubefs/docker/conf/metanode.json:/cfs/conf/metanode.json -v /home/yxt/cubefs/docker/script/start_meta.sh:/cfs/script/start.sh --restart on-failure --privileged     --network  host   docker.io/cubefs/cbfs-base:1.0-golang-1.17.13 /bin/sh /cfs/script/start.sh


docker run -d --name metanode3 -v /date/disk/metanode3/data:/cfs/data -v /home/yxt/cubefs/build/bin:/cfs/bin:ro -v /data/disk/metanode3/log:/cfs/log -v /home/yxt/cubefs/docker/conf/metanode.json:/cfs/conf/metanode.json -v /home/yxt/cubefs/docker/script/start_meta.sh:/cfs/script/start.sh --restart on-failure --privileged     --network  host   docker.io/cubefs/cbfs-base:1.0-golang-1.17.13 /bin/sh /cfs/script/start.sh
```
- datanode

```
docker run -d --name datanode1 -v /date/disk/datanode1/data:/cfs/data -v /home/yxt/cubefs/build/bin:/cfs/bin:ro -v /data/disk/datanode1/log:/cfs/log -v /home/yxt/cubefs/docker/conf/datanode.json:/cfs/conf/datanode.json -v /home/yxt/cubefs/docker/script/start_datanode.sh:/cfs/script/start.sh --restart on-failure --privileged     --network  host   docker.io/cubefs/cbfs-base:1.0-golang-1.17.13 /bin/sh /cfs/script/start.sh


docker run -d --name datanode2 -v /date/disk/datanode2/data:/cfs/data -v /home/yxt/cubefs/build/bin:/cfs/bin:ro -v /data/disk/datanode2/log:/cfs/log -v /home/yxt/cubefs/docker/conf/datanode.json:/cfs/conf/datanode.json -v /home/yxt/cubefs/docker/script/start_datanode.sh:/cfs/script/start.sh --restart on-failure --privileged     --network  host   docker.io/cubefs/cbfs-base:1.0-golang-1.17.13 /bin/sh /cfs/script/start.sh

docker run -d --name datanode3 -v /date/disk/datanode3/data:/cfs/data -v /home/yxt/cubefs/build/bin:/cfs/bin:ro -v /data/disk/datanode3/log:/cfs/log -v /home/yxt/cubefs/docker/conf/datanode.json:/cfs/conf/datanode.json -v /home/yxt/cubefs/docker/script/start_datanode.sh:/cfs/script/start.sh --restart on-failure --privileged     --network  host   docker.io/cubefs/cbfs-base:1.0-golang-1.17.13 /bin/sh /cfs/script/start.sh
```


- Deployment results

<img width="649" alt="image" src="https://github.com/cubefs/cubefs/assets/30840540/17a34e5d-9087-444d-a2fc-64bc116566a8">

<img width="648" alt="image" src="https://github.com/cubefs/cubefs/assets/30840540/6a44d527-95e8-4b8a-9597-0b00da9ade47">


<img width="652" alt="image" src="https://github.com/cubefs/cubefs/assets/30840540/704d88f6-9fb2-4363-94a4-5af4d7095ef0">

- Configure master node information

<img width="533" alt="image" src="https://github.com/cubefs/cubefs/assets/30840540/98b87aa2-1fce-416a-a743-1a37aaa75b89">

Then we can use the cfs-cli tool to verify!!!

**Comment by ytyuanxi** [comment]
The design of my simple configuration file:

data_dir: store master, metanode, datanode in the running process of various files, such as log. default use global configuration, support custom directory.

disk: the disk that the datanode mounts, different nodes can choose which disk to mount the effort

```


global:
  ssh_port: 22
  container_image: docker.io/cubefs/cbfs-base:1.0-golang-1.17.13
  data_dir: /data
  variable:
    target: 0.0.1

master:
  config:
    listen: 17010
    prof: 17020
    data_dir: /data

metanode:
  config:
    listen: 17210
    prof: 17220
    data_dir: /data

datanode:
  config:
    listen: 17310
    prof: 17320
    data_dir: /data



deplopy_hosts_list:
  master:
    hosts:
      - 192.168.128.128
      - 192.168.128.129
      - 192.168.128.130
  metanode:
    hosts:
      - 192.168.128.134
      - 192.168.128.135
      - 192.168.128.136
  datanode:
    - hosts: 192.168.128.131
      disk:
        - /data0
    - hosts: 192.168.128.132
      disk:
        - /data0
        - /data1
    - hosts: 192.168.128.133
      disk:
        - /data2
        - /data3


```

**Comment by ytyuanxi** [comment]
Users can use the - h or -- help option to view usage information- The v or -- version option is used to output version information.

The command section includes:

- cluster
  - init ： Initialize the cluster, read the configuration file, establish a cluster password free connection, and pull containers on each host
  - info ：Display cluster information, service name | container name | host IP|
  - clear：Clear the deployment files of each host on the cluster

- start ：Start the service, which starts all services according to the configuration file by default
  - master：Start all masters individually
    - --ip：Specify to start the service on this IP, check if the IP is present in the configuration file, and if not, write the IP to the configuration file
  - metanode：Start all metanodes individually
    - --ip： Specify to start the service on this IP, check if the IP is present in the configuration file, and if not, write the IP to the configuration file
  - datanode：Start all datanodes individually
    - --ip ：Specify to start the service on this IP, check if the IP is present in the configuration file, and if not, write the IP to the configuration file

- stop ： Close the service, and by default, all services are closed
  - master：Turn off the master separately
    - --ip：Turn off the specified IP service	
  - metanode：Close all containers of metanode separately
    - --ip：Turn off the specified IP service
  - datanode：Close datanode separately
    - --ip：Turn off the specified IP service

- restart 
  - master：Restart the master separately
    - --ip：Restart the specified IP service
  - metanode：Restart all containers of metanode separately
    - --ip：Restart the specified IP service
  - datanode：Restart datanode separately
    - --ip：Restart the specified IP service

**Comment by ytyuanxi** [comment]
代码地址：[https://github.com/ytyuanxi/yxt-deploy-cli](url)

- Interface of the deploy cli tool

![image](https://github.com/cubefs/cubefs/assets/30840540/ecada8d4-7afa-4dfd-ae47-2b8751d06087)

- cluster

![image](https://github.com/cubefs/cubefs/assets/30840540/027d040b-f609-4a64-814f-a8026d2c28e9)

- The specific design and implementation of cluster init

specific design
 
1.  Read Configuration File
2. Obtain the IP address of the current host
3. Establish a secure connection from the current node to other nodes
4. for each node:
  a. Check if Docker is installed and installed
  b. Check if the Docker service is started and started
  c. Pull Mirror

implementation

![image](https://github.com/cubefs/cubefs/assets/30840540/b4f61cff-9ec0-4cb0-8dbb-305ecc4c5c38)

**Comment by ytyuanxi** [comment]
start master:  start all master from config.yaml
step:

1. Read configuration file
2. Obtain the masters' peers
3. for each master: 
3.1 assign the master ID starting from 1 in order
3.2 generate a corresponding master{id}.json file for each master
3.3 transfer corresponding files to the target node
3.4 check and delete containers with the same name on this node
3.5 start service


Implementation effect

<img width="1244" alt="image" src="https://github.com/cubefs/cubefs/assets/30840540/e182b7dd-237c-46c5-98c0-20a8153337d2">


Improvement plan

Except for the master{id}. json file, other files only need to be transferred once during init. When there are containers on the target node that are using related files, the transfer of files will fail. It is necessary to first check whether there are containers on the target host that are using related files

**Comment by ytyuanxi** [comment]
`go run deploy_cli.go  cluster init`

![image](https://github.com/cubefs/cubefs/assets/30840540/8fe08684-46b2-4960-8b77-cf647ce5e160)

`go run deploy_cli.go  cluster info`

![image](https://github.com/cubefs/cubefs/assets/30840540/2889b0e5-0347-4924-8be3-8f1f756ad2cd)

`go run deploy_cli.go start master`

![image](https://github.com/cubefs/cubefs/assets/30840540/8c761087-3317-4002-95c0-fcf6b6f489ae)

bug：Some node configuration files are mapped to directories

`go run deploy_cli.go start metanod`

![image](https://github.com/cubefs/cubefs/assets/30840540/02f98965-2c83-4d06-8ec3-5761b136dba2)


`go run deploy_cli.go  start metanode  --ip 10.1.0.44`
<img width="659" alt="image" src="https://github.com/cubefs/cubefs/assets/30840540/241dd6d5-8059-4cf8-971f-86282c65c0cb">


`go run deploy_cli.go start datanode`

![image](https://github.com/cubefs/cubefs/assets/30840540/6bd0796e-65f3-412d-991c-62e0416017fd)

`go run deploy_cli.go  start datanode --ip 10.1.0.44`

<img width="654" alt="image" src="https://github.com/cubefs/cubefs/assets/30840540/523caf91-9dcb-478f-80c0-5eeb4ae35e70">

`go run deploy_cli.go start --all`

<img width="746" alt="image" src="https://github.com/cubefs/cubefs/assets/30840540/b99f50e3-91a4-497f-acce-5bcf86ac3d0c">


`go run deploy_cli.go cluster info`

there are some bug need to fixed

<img width="627" alt="image" src="https://github.com/cubefs/cubefs/assets/30840540/2ada1448-2772-4b3f-b52d-49ef572311cb">

`go run deploy_cli.go stop master`
<img width="459" alt="image" src="https://github.com/cubefs/cubefs/assets/30840540/7f2d59e8-f9f3-4d6a-9063-547a1a6bc69c">

`go run deploy_cli.go stop metanode`

<img width="464" alt="image" src="https://github.com/cubefs/cubefs/assets/30840540/052ac315-d2bc-4c7e-8ca7-765f2e413b8f">



`go run deploy_cli.go stop datanode`
<img width="536" alt="image" src="https://github.com/cubefs/cubefs/assets/30840540/73b95ea3-fc06-409c-a22c-2b5e6d0ea876">


`go run deploy_cli.go stop datanode --ip 10.1.0.44`

<img width="561" alt="image" src="https://github.com/cubefs/cubefs/assets/30840540/b973a257-f7d5-4de0-a740-8d5d7545a4b7">

`go run deploy_cli.go stop metanode --ip 10.1.0.44`

<img width="616" alt="image" src="https://github.com/cubefs/cubefs/assets/30840540/1be3d89d-9e19-4662-bb86-aa8a3f97a222">

**Comment by ytyuanxi** [comment]
SOME BUG

bug1：SSH secure connection will be established twice
![image](https://github.com/cubefs/cubefs/assets/30840540/9ecc9294-455f-484e-aef8-ed13fe1298fa)

bug2：Some configuration files are mapped to JSON
![image](https://github.com/cubefs/cubefs/assets/30840540/43d64d5f-ce1c-4fa1-b80d-492b9ae5a72b)

bug3：master leader

![image](https://github.com/cubefs/cubefs/assets/30840540/1678409f-ba89-4e42-b9bb-1f8360408c1c)

![image](https://github.com/cubefs/cubefs/assets/30840540/8f57d74a-d07c-4bb9-bac1-45eac3c0c586)


bug4：The same command is normal on local virtual machines and abnormal on cloud machines


`docker run -d --name master3 -v /data/disk/master3/data:/cfs/data -v /data/bin:/cfs/bin:ro -v /data/disk/master3/log:/cfs/log -v /data/conf/master3.json:/cfs/conf/master.json -v /data/script/start_master.sh:/cfs/script/start.sh --restart on-failure --privileged     --network  host   docker.io/cubefs/cbfs-base:1.0-golang-1.17.13 /bin/sh /cfs/script/start.sh`

The corresponding port is not occupied

VM：
<img width="752" alt="image" src="https://github.com/cubefs/cubefs/assets/30840540/fedce347-0158-44f5-9264-ed933012b2ae">

cloud：
<img width="752" alt="image" src="https://github.com/cubefs/cubefs/assets/30840540/ed4ec317-8b89-431c-8406-f0079fb69a96">

<img width="617" alt="image" src="https://github.com/cubefs/cubefs/assets/30840540/6646c396-384a-44ed-abe1-610f50e20c3d">


myfirewall

<img width="504" alt="image" src="https://github.com/cubefs/cubefs/assets/30840540/34eb29d2-4c56-4caf-936e-1e5576c981ab">

**Comment by ytyuanxi** [comment]
new bug：Failed to create volume

<img width="757" alt="image" src="https://github.com/cubefs/cubefs/assets/30840540/eb785dee-7f25-410f-9303-059f6712e068">

**Comment by ytyuanxi** [comment]
need to install fuse，adding fuse detection in the init command

<img width="1280" alt="image" src="https://github.com/cubefs/cubefs/assets/30840540/a83a92d6-00e2-4ed5-8304-6c5694b71ef4">

success！！
<img width="755" alt="image" src="https://github.com/cubefs/cubefs/assets/30840540/0c4f9488-b754-4828-b8fb-926a5fa26de3">

**Comment by baijiaruo** [comment]
Can it be mounted normally through deploy-cli cluster init and start?

**Comment by ytyuanxi** [comment]
Need to detect whether fuse is installed in the init function，the firewall also needs to be rechecked。

**Comment by ytyuanxi** [comment]
The following methods cannot install fuse through the go language. Write fuse into the markdown document as a dependency installation.

The current firewall is in a completely closed state. Do we need to be precise about which ports to open?

<img width="1006" alt="image" src="https://github.com/cubefs/cubefs/assets/30840540/b7d8154a-fd54-495c-964d-988c2752c41c">


<img width="1078" alt="image" src="https://github.com/cubefs/cubefs/assets/30840540/cf1dd3f0-b0ec-4cf0-88b6-6eeaa07fa8c1">

<img width="878" alt="image" src="https://github.com/cubefs/cubefs/assets/30840540/39153dca-078d-410b-a3bb-197a3ed04f1b">

**Comment by ytyuanxi** [comment]
-The v option will display the current version of the deploy tool and the version of the bin file


<img width="869" alt="image" src="https://github.com/cubefs/cubefs/assets/30840540/aafab884-4d73-42f0-abea-74583c8962a4">

**Comment by ytyuanxi** [comment]
The restart and clear functions have not been completed yet

**Comment by ytyuanxi** [comment]
# clear

`go run deploy_cli.go  cluster clear`

<img width="998" alt="image" src="https://github.com/cubefs/cubefs/assets/30840540/8dafb685-867f-4555-887b-050239584c40">

If you want to clear the container images in the cluster, you need to stop and delete all containers based on the current image

<img width="1255" alt="image" src="https://github.com/cubefs/cubefs/assets/30840540/0ac96c38-e2a6-49bd-9aa8-325bc6b9dafb">

**Comment by ytyuanxi** [comment]
# restart

`go run deploy_cli.go restart -a`

<img width="704" alt="image" src="https://github.com/cubefs/cubefs/assets/30840540/66ba29af-92e8-45e7-8dd3-85cdfbd4fa2d">

`go run deploy_cli.go  restart master`

<img width="695" alt="image" src="https://github.com/cubefs/cubefs/assets/30840540/754e3f62-bd02-4aca-afd5-a059ef8c8948">

`go run deploy_cli.go  restart metanode`

<img width="695" alt="image" src="https://github.com/cubefs/cubefs/assets/30840540/d1779685-3300-43c1-8f8d-f546b67bbf92">

`go run deploy_cli.go  restart metanode --ip 192.168.128.128`

<img width="690" alt="image" src="https://github.com/cubefs/cubefs/assets/30840540/dae74c85-63b7-4b03-90ca-55fb12e22c96">

`go run deploy_cli.go  restart datanode`
<img width="693" alt="image" src="https://github.com/cubefs/cubefs/assets/30840540/b90041bb-c8e9-4ad4-981e-a9d127f88446">

`go run deploy_cli.go  restart datanode --ip 192.168.128.128`

<img width="691" alt="image" src="https://github.com/cubefs/cubefs/assets/30840540/587768b0-b5e5-4d63-a54e-8258186ffa4c">
