### ISSUE TITLE
[Bug]: Some issues encountered and existing solutions while compiling Blobstore.

### ISSUE THREAD

**Issue by aFlyBird0** [cubefs/cubefs#1963]
## Backgroud

I encountered some issues while compiling blogstore, and through communication with @pengtianyue025 （thanks a lot!!!), I solved some of the problems in my own way (which may not be the optimal solution). Perhaps this information will be useful to other developers.

**The environment**

* OS: Ubuntu 22.04 amd64 which installed in [multipass vm](https://multipass.run/docs), the host os is ubuntu 20.04 amd64
* `gcc -dumpversion`: 11
* cmake version 3.22.1

## 1. GCC(marjor 11) regard warnings as errors, so that the compile failed

**Bug && To Reproduce**

1. (use gcc 11)
2. cd cubefs/blobstore
3. rm .deps/lib/librocksdb.a  # if exists
4. ./run.sh

`run.sh` will execute `build.sh`, and there are many warnings when compiling `librocksdb.a`, and gcc regard them as errors.

screenshots here:

![image](https://github.com/cubefs/cubefs/assets/36830265/80be8a1e-e21b-47cd-ad13-0efdf208577d)

Although the `build.sh` already has handling for ignoring warnings, it seems insufficient. 

https://github.com/cubefs/cubefs/blob/d34dc4010dfb4e55e651c5390ce1badfe2ccf992/blobstore/build.sh#L132

 I tried adding a -w option at the end to ignore all warnings, and it worked. (But this is obviously not elegant, so I raised an issue.)

The final code looks like this: `FLAGS="-Wno-error=deprecated-copy -Wno-error=pessimizing-move -w"`

## 2. blobstore faild to flock

**Bug**

<img width="723" alt="image" src="https://github.com/cubefs/cubefs/assets/36830265/f22a2d91-df9a-4823-a02e-9bd7fe0c6b5f">

** How to Reproduce**

I didn't do anything, just execute `sudo ./run.sh --consul` at `cubefs/blobstore`. 
I even try to execute `chmod 777 -R` to whole root cubefs dir. It doesn't work.

**Analyze and temp resolution**

The errror is from:

<img width="1321" alt="image" src="https://github.com/cubefs/cubefs/assets/36830265/c34c51d3-873a-40dc-bbf0-e10e1197b00a">

 I guess `blobnode.flock` is just a regular file, but cubefs simulates lock operations by creating/reading this file (only successful creation and reading means the lock has been acquired).

So I execute `touch `blobnode.flock` and re-run `run.sh`, it did work.

I even tried modifying the .conf file, changing the default flock name to blobnode2.flock, but I still got the same error, so it's not a problem of another process acquiring the file lock. 

Therefore, I still can't understand why the file cannot be created correctly, because [run.sh](http://run.sh/) has already automatically created many additional files in this directory, so theoretically, it should have the necessary permissions. (maybe due to 22.04 or multipass?)

This is reponse from ChatGPT:

![image](https://github.com/cubefs/cubefs/assets/36830265/35f5d587-dbfa-4dd0-92d2-646054b65ff8)

Maybe we could use `os.O_RDWR|os.O_CREATE` rather than `os.O_CREATE|os.O_RDONLY`?

**Comment by aFlyBird0** [comment]
Update: When I change `os.O_CREATE|os.O_RDONLY` to `os.O_RDWR|os.O_CREATE`, it could open `blobnode.flock` successfully.

**Comment by aFlyBird0** [comment]
> You can check if the latest version of the master branch has already solved the first issue. And the second issue need @JasonHu520 confirm

Sorry, it doesn't work

![image](https://github.com/cubefs/cubefs/assets/36830265/934cb689-caab-4dbc-af03-b0b23dff1412)
![image](https://github.com/cubefs/cubefs/assets/36830265/c099dd00-7c17-46f9-84a8-35a9262284f8)

**Comment by pengtianyue025** [comment]
you can try again with master branch

**Comment by aFlyBird0** [comment]
> you can try again with master branch

Cool!  (`cd cubefs && make blobstore`)
<img width="484" alt="image" src="https://github.com/cubefs/cubefs/assets/36830265/281061f0-0d0a-4484-997a-de2bbc36b34f">

**Comment by true1064** [comment]
@aFlyBird0 seem that your blobstore compiling is success, so I close this issue.
plz re-open it if necessary.
