### ISSUE TITLE
[Feature]: cubefs surpport autofs mount

### ISSUE THREAD

**Issue by leonrayang** [cubefs/cubefs#1977]
**Is your feature request related to a problem? Please describe.**
build  ladp+automount+cubefs-client automition mount workflow，Support for easier mount management

**Describe the solution you'd like**
cubefs launches tools and detailed process instructions to help users quickly use autofs+cubefs

**Comment by Victor1319** [comment]
@leonrayang good job

**Comment by true1064** [comment]
done: https://github.com/cubefs/cubefs/pull/1973
