### ISSUE TITLE
[Feature]: The cli tool supports creating 1, 2 copies, and changing the number of copies

### ISSUE THREAD

**Issue by leonrayang** [cubefs/cubefs#1978]
**Is your feature request related to a problem? Please describe.**
The cli tool supports creating 1, 2 copies, and changing the number of copies

**Describe the solution you'd like**
It has been a long time since the single-replica and double-replicashave been released, and tools need to be completed

**Comment by true1064** [comment]
done: https://github.com/cubefs/cubefs/pull/1973
