### ISSUE TITLE
[Feature]:  Support 2replicas volume down to 1 replica and recycling resources

### ISSUE THREAD

**Issue by leonrayang** [cubefs/cubefs#1979]
**Is your feature request related to a problem? Please describe.**
 Consider the cost, support 2replicas volume down to 1 replica and recycling resources

**Describe the solution you'd like**
recycling resources need consider thes system load

**Comment by Victor1319** [comment]
@leonrayang

**Comment by true1064** [comment]
done: https://github.com/cubefs/cubefs/pull/1973
