### ISSUE TITLE
[Feature]: support uid space limitation

### ISSUE THREAD

**Issue by leonrayang** [cubefs/cubefs#1980]
**Is your feature request related to a problem? Please describe.**
In many cases, multiple users share a volume, so using uid as the dimension, setting the upper limit of capacity can facilitate the fine-grained management of volumes

**Describe the solution you'd like**
Data accuracy, relative real-time, priority to system load impact

**Comment by Victor1319** [comment]
@leonrayang

**Comment by true1064** [comment]
done: https://github.com/cubefs/cubefs/pull/1973
