### ISSUE TITLE
[Feature]: follower support  metrics report

### ISSUE THREAD

**Issue by leonrayang** [cubefs/cubefs#1982]
**Is your feature request related to a problem? Please describe.**
Currently only master leader have metrics report, the monitor cann't get the follower information. and some cases needs the follower's status . Here need the follower support  metrics report

**Describe the solution you'd like**
Do monitor on follower's raft snapshot status, and monitor the leader miss status.

**Comment by true1064** [comment]
done: https://github.com/cubefs/cubefs/pull/1973
