### ISSUE TITLE
[Feature]: Strengthen the disk crc check

### ISSUE THREAD

**Issue by leonrayang** [cubefs/cubefs#1984]
**Is your feature request related to a problem? Please describe.**
Strengthen the disk crc check，currently the crc have the wrong report, cann't be used in monitor, and the crc recalculate only happend at the write request and on the definite block.

**Describe the solution you'd like**
1st Correct the scene of crc inconsistency caused by asynchronous modification caused by raft
2nd build the tool to check the extent in real time
3rd build the meachnism to recalculate the crc if the system load can stand

**Comment by true1064** [comment]
done: https://github.com/cubefs/cubefs/pull/1973
