### ISSUE TITLE
[Bug]: Fix the problem which snapshot was interrupted but saved the metadata 

### ISSUE THREAD

**Issue by xiangcai1215** [cubefs/cubefs#1986]
**Describe the bug**
During the Raft snapshot execution process, the process was interrupted, but the metadata of the snapshot was saved. This resulted in incomplete data on the meta partition or data partition.

**Comment by Victor1319** [comment]
@JasonHu520

**Comment by true1064** [comment]
done: https://github.com/cubefs/cubefs/pull/1973
