### ISSUE TITLE
[Feature]: cli tool support 2-replica dp decommission

### ISSUE THREAD

**Issue by bboyCH4** [cubefs/cubefs#1987]
**Is your feature request related to a problem? Please describe.**
Now cli tool only supports 3-replica dp decommission, if you want to decommission 2-replica dp, http request is the only way

**Describe the solution you'd like**
 cli tool 's decommission command supports 2-replica decommission

**Comment by Victor1319** [comment]
it's useful

**Comment by true1064** [comment]
done: https://github.com/cubefs/cubefs/pull/1973
