### ISSUE TITLE
[Feature]: ObjectNode CORS

### ISSUE THREAD

**Issue by tangdeyi** [cubefs/cubefs#1988]
CORS supports simple request and preflight request.

The new bucket CORS supports commonly used CORS headers, e.g.
"Origin"
"Access-Control-Request-Method"
"Access-Control-Request-Headers"
"Access-Control-Allow-Origin"
"Access-Control-Allow-Credentials"
"Access-Control-Max-Age"
"Access-Control-Allow-Methods"
"Access-Control-Allow-Headers"
"Access-Control-Expose-Headers"

**Comment by xiaochunhe** [comment]
looking forward to this feature, which version will it be released in?
