### ISSUE TITLE
[Bug]: master dead lock caused by mps rwlock

### ISSUE THREAD

**Issue by leonrayang** [cubefs/cubefs#1991]
**Describe the bug**
1) getMetaPartitionsView hold mps read lock need mp lock
2) splitMetaPartition need mps lock but find the read lock on,then hang wait the read return,but trigger a lock waitting status
3) checkEnd hold mp lock and need mps read lock but the mps reads lock be hang by 2)'s lock preparition

according to the step upon, the deallock happened

**Environment**
3.2.1

**Comment by Victor1319** [comment]
it's a bug, hope you to fix it

**Comment by true1064** [comment]
done: https://github.com/cubefs/cubefs/pull/1973
