### ISSUE TITLE
[Bug]: create volume init data error but can get volume

### ISSUE THREAD

**Issue by xiangcai1215** [cubefs/cubefs#2019]
**Describe the bug**
An init data partition error results in insufficient data partitions in a volume's partition map. However, the volume already exists in the system, so it can be found in the master.

**Environment**
Describe your server system version, kernel version

**To Reproduce**

**Expected behavior**

**Additional context**

**Comment by true1064** [comment]
There seems to be a problem

**Comment by true1064** [comment]
@xiangcai1215  plz check this out, seems you have fixed it?

**Comment by true1064** [comment]
confirmed that it is a bug. plan to fix it in develop-3.4.0
