### ISSUE TITLE
[Bug]: the metrics dp_missing_Leader_count and dp_no_leader not condsider cold volume's data partition

### ISSUE THREAD

**Issue by true1064** [cubefs/cubefs#2050]
**Describe the bug**
cold volume(EC)'s data partition has no concept of leader.
If a cluster has a cold volume with data partition，the wrong metrics dp_missing_Leader_count dp_no_leader comes out.

**Environment**
CubeFS release-v3.2.1

**To Reproduce**
create cold volume with data partitions; all datanode is active; nothing else need to do,
just wait for the the dp_missing_Leader_count(default 1min)  and dp_no_leader(default 10min) metrics comes out.

**Expected behavior**
the metrics dp_missing_Leader_count and dp_no_leader not condsider cold volume's data partition

**Comment by xiangcai1215** [comment]
which version

**Comment by true1064** [comment]
> which version

v3.2.1
