### ISSUE TITLE
[Bug]:  when volume is deleted, data partition view cache of follower master still genarates metrics and warn log

### ISSUE THREAD

**Issue by true1064** [cubefs/cubefs#2072]
**Describe the bug**
when volume is deleted, data partition view cache of follower master still genarates metrics and warn log.
see func (mgr *followerReadManager) checkStatus() and (mm *monitorMetrics) setVolNoCacheMetrics() 

**Environment**
branch develop-3.3.0

**To Reproduce**
delete a volume and wait 5min for the metrics and warn log

**Expected behavior**
no related metrics and warn log when volume is deleted

**Comment by baijiaruo** [comment]
Are there similar issues in other scenarios?

**Comment by true1064** [comment]
this bug was introduced in branch develop-3.3.0 and has never merged into master branch.
