### ISSUE TITLE
[Feature]:  pprof port of client need be protect and only be accessed locally

### ISSUE THREAD

**Issue by leonrayang** [cubefs/cubefs#2080]
**Is your feature request related to a problem? Please describe.**

_ "net/http/pprof" of client has the risk to reveal details of running env and data while running on public cloud.

**Environment**
Release 3.2.1

**Describe the solution you'd like**
Only accessible via local requests to analysis online issues

**Comment by true1064** [comment]
some users may need to access pprof port remotely.  need to add a configuration  as a switch
