### ISSUE TITLE
[Bug]: The compiled version of rocksdb is not compatible with the old version

### ISSUE THREAD

**Issue by JasonHu520** [cubefs/cubefs#2082]
**Describe the bug**
1. "Snappy not supported or corrupted Snappy compressed block contents" appears when the new version of the packaged image reads the data of the old version

**Environment**
Linux version 3.10.0-957.27.2.el7.x86_64

**Expected behavior**
Read old versions of data normally

**Comment by cessory** [comment]
I'll change the complilation parameters and recomplie rocksdb to fix it.
