### ISSUE TITLE
[Bug]: lock happend while domainOn enabled and dpSplit metaPartition

### ISSUE THREAD

**Issue by leonrayang** [cubefs/cubefs#2101]
**Describe the bug**
lock happend while domainOn enabled and dpSplit metaPartition

sync.runtimeSemacauireMutex+x46
sync.(*Mutex).lockSlow+9x194
sync.(*Mutex).Lock+x8f
sync.(*RWMutex).Lock+x21
github.com/cubefs/cubefs/master.getMetaPartitionView+@x113
titionsView+@x25bgithub.com/cubefs/cubefs/master.(*Vol).getMetapa
github.com/cubefs/cubefs/master.(*Vol).updateview(che+x22c
github.com/cubefs/cubefs/master.(*Cluster).isFaultDomain+@x249
github.com/cubefs/cubefs/master.(*Vol).doCreateMetaPartition+@xdd
github.com/cubefs/cubefs/master.(*Vol).doSplitMetaPartition+@x3@e
github.com/cubefs/cubefs/master.(*Vol).splitMetaPartition+@x105
github.com/cubefs/cubefs/master.(*Cluster).updateInodeIDupperBound+0x265

**Environment**
3.2.1

**Comment by Victor1319** [comment]
@leonrayang
