### ISSUE TITLE
[Bug]: Quota dual directory configuration optimization problem

### ISSUE THREAD

**Issue by baijiaruo** [cubefs/cubefs#2107]
**Describe the bug**
1. Set up dual directories. If the second one is just ',', it will be used as the root directory, and there will be one more row when querying, but it is unrealistic. paht only has pid and riniode data, which needs to be optimized.
---This path is not very uniform, dir6 can be recognized without /. If it is just a comma, it will be recognized as the root directory. It is better to start from the root directory according to the unified
2. This prompt can be optimized. Add a better directory name. Which directory is repeated is more intuitive. This requires an additional query.This is not necessarily easy to do, the master side does not know the relationship between the directory and the inode, it is purely comparing the inodeId.The path where your master can find this piece of data is the directory. Why do you say you can’t find it?
3. When setting multiple directories, three or seven can be used. It is recommended to increase the upper limit to prevent misuse
4. 4 used files are displayed after the quota synchronization of 7 directories is created
5. Let’s see if this list can be sorted. Every search is in random order.

**Comment by xiangcai1215** [comment]
which version？
