### ISSUE TITLE
[Feature]: add name resolver for master sdk

### ISSUE THREAD

**Issue by wuchunhuan** [cubefs/cubefs#2136]
**Is your feature request related to a problem? Please describe.**
1.metanode and datanode can not use master domain which point to a proxy server
2.when master nodes changed, master address in metanode and datanode config file needs to update and, a restart need to be done

**Describe the solution you'd like**
master domain name will be resolved to real ip, and be updated timely.

**Comment by true1064** [comment]
done: https://github.com/cubefs/cubefs/pull/2132
