### ISSUE TITLE
[Feature]: needs a settable swich to allow or forbid metaPartition decommission in cluster

### ISSUE THREAD

**Issue by true1064** [cubefs/cubefs#2139]
**Is your feature request related to a problem? Please describe.**
In some operation and maintenance scenarios, we hope to be able to forbid metaPartition decommission in cluster for a  period of time, and then allow it again.

**Describe the solution you'd like**
needs a settable swich to allow or forbid metaPartition decommission in cluster

**Comment by baijiaruo** [comment]
Do I need to add a configuration item?

**Comment by true1064** [comment]
> Do I need to add a configuration item?

no. the swich is set/unset by cmd, and will be stored persistently
