### ISSUE TITLE
[Bug]: meta partition raft follower may apply wrong cursor when apply snapshot from leader

### ISSUE THREAD

**Issue by true1064** [cubefs/cubefs#2149]
**Describe the bug**
each meta partition  maintains a cursor for generate inodeId. the cursor can only be monotonically incremented.
which means onece inodeId=N is generated, inodeIds be generated later must be greate than N, even the inodeId=N has been deleted.

But when meta partition raft leader send snapshot to followers, the cursor is not contained in snapshot.
when applies snapshot, the follower use the max inodeId of snop.Op opFSMCreateInode as the cursor.
But  the  max inodeId of snop.Op opFSMCreateInode may be less than the actual cursor of leader! see this senario:
(1)  meta partition's current max inodeID of files in the FS is N, cursor is N.
(2)  the file of inodeID=N is deleted, max inodeID of files in the FS becomes N-M, cursor is still N
(3)  the leader took an raft local snapshot, and the raft log of deletion of inodeID=N has been truncated out.
(4) leader send snapshot to follwer,  the follwer took inodeID=N-M as cursor, but leader's cursor is still N.

**Environment**
Describe your server system version, kernel version
CubeFS version < 3.3.0

**To Reproduce**
(1) modify func (m *MetaNode) startRaftServe(), set NumOfLogsToRetain as 1, to make reproduce more easyly.
(2) rebuild the codes, deploy a cluster, create a volume and mount it.
(3) create some files in the mount point path, choose a meta partition to test, and make it has mutiple inodes.
(4) delete the file of max inodeID of the chosen meta partition.
(5) make meta partition deommission onf the chosen meta partition, trigger the leader send snapshot to the newly add-in follower.
(6) check the curors of leader and th newly add-in follow, the former is larger than the latter

**Expected behavior**
when follower's cursor should be consistent with the leader when  apply snapshot.

**Additional context**
Solution suggestion：
meta partition's raft leader sends snapshot to follower,  add cursor filed in the snapshot, to make follower's apply cursor consistent with the leader.

Compatibility consideration：
In cluster upgrading senario, metaNodes of different snapshot versions exists at the same time,
to avoid problems, snapshot is not allowed to be applied if snapshot versions not match.
Need to think carefully about compatibility issues of upgrading.

**Comment by xiangcai1215** [comment]
Yes, The cursor not in the snapshot will have the potential to cause this problem.

**Comment by xiaochunhe** [comment]
This bug reproduction process is very clear，well done！
