### ISSUE TITLE
[Feature]: metaNode's raft retainlogs parameter should be changed to configurable,  by config file

### ISSUE THREAD

**Issue by true1064** [cubefs/cubefs#2151]
**Is your feature request related to a problem? Please describe.**
In operation and maintenance practice we sometimes need to modify raft retainlogs.
At present, module mater and some others support  configure raft retainlogs by config file, but metaNode not yet.

**Describe the solution you'd like**
 metaNode's raft retainlogs parameter should be changed to configurable by config file

**Comment by JasonHu520** [comment]
Great, this gives the flexibility to adjust the progress of snapshots

**Comment by true1064** [comment]
This feature is done, commit: 859d8b4ed2305eeba3ffc658b3e6f557144e4589
