### ISSUE TITLE
[Bug]: connection leak

### ISSUE THREAD

**Issue by KM-SF** [cubefs/cubefs#2175]
**Describe the bug**
If lbclient does not configure a timeout and accesses an excluded clustermgr node, then this link will not be recycled, and there will be a leakage problem

**Environment**

- CentOS Linux release 7.6.1810
- golang 1.19

**To Reproduce**
1. Remove a clustermgr node
2. The client does not configure a timeout
3. Use lbclient to access the clustermgr node
4. Use the netstat command to view the TPC connection, you will see that the connection will not be released

**Expected behavior**
The HTTP connection is expected to release

**Additional context**
The body needs to be closed before retrying. (blobstore/common/rpc/lb.go +303)
Otherwise http will wait for you to read or close the body. (net/http/transport.go +2214)

**Comment by sejust** [comment]
fix on the way

**Comment by JasonHu520** [comment]
good problem
