### ISSUE TITLE
[Bug]:  In Fuse client, a buffer will be allocated to two writer of different files if this buffer was freed twice by last writer, which causes inconsistence.

### ISSUE THREAD

**Issue by M1eyu2018** [cubefs/cubefs#2257]
**Describe the bug**
In Fuse client, a buffer will be allocated to two writer of different files if this buffer was freed twice by last writer, which causes inconsistence.

**Comment by true1064** [comment]
Done: https://github.com/cubefs/cubefs/pull/2265
