### ISSUE TITLE
[Perf]: Reduce objectnode unnecessary metadata operation.

### ISSUE THREAD

**Issue by tangdeyi** [cubefs/cubefs#2276]
**Describe the problem**
1、Objectnode deletes object by unlinking and evicting inode. But evicting inode is unnecessary.
2、Objectnode complete multipart by processing the redundant metadata synchronously.

**Environment**
version 3.2.1

**Comment by xiaochunhe** [comment]
Can you attach the corresponding code and briefly describe the solution?

**Comment by xiaochunhe** [comment]
> version 3.2.1

does it exist in versions lower than 3.2.1 ?

**Comment by tangdeyi** [comment]
> Can you attach the corresponding code and briefly describe the solution?
For example, the code related to the first question：
[https://github.com/cubefs/cubefs/blob/54608a6016b752cd73d8fa24507bbd55a8a184f2/objectnode/fs_volume.go#L915C21-L915C21](url)
Deleting object through objnode will cause the following things：
1. The object dentry will be deleted by OpMetaDeleteDentry, which will delete obj dentry.
2. The object inode  will be deleted by OpMetaUnlinkInode, which will unlink inode and add inode to freelist when nlink is 0.
3. The object inode will be evicted by OpMetaEvictInode, which will set inode deleted marker.
But the step3 is unneccessry, the object becomes invisible after step1. And data space will be freed asynchronously through step2.

**Comment by tangdeyi** [comment]
> > version 3.2.1
> 
> does it exist in versions lower than 3.2.1 ?

yes，it is an old problem.
