### ISSUE TITLE
[Bug]: Upgrade compatibility needs to be considered after uinqID feature is introduced

### ISSUE THREAD

**Issue by true1064** [cubefs/cubefs#2337]
**Describe the bug**
 uinqID feature is introduced recently, refer to:
 pr: https://github.com/cubefs/cubefs/pull/2283 
 issue: https://github.com/cubefs/cubefs/issues/2256

But the upgrade compatibility not handled very well:
(1) when meta partition loading local snapshot files created by an older version, it will faild for lacking uniqId related files.
(2) when meta partition raft leader send snapshot to followers with uniqId related info, if a follower is older version, it will fail to apply the snapshot for not recognizing the new op code.

**To Reproduce**
(1) failure  occur when loading local snapshot files: create an cluster and an volume wiht versions before uinqID feature is introduced, then upgrade metenode to uinqID feature version.
(2) older version mp follower failed to apply raft snapshot: the mp leader is uinqID feature version , the follower is older version, set raft retianLogs as 1 in config file, create some files, decommision mp to trigger raft snapshot sync to the new replica.

**Expected behavior**
(1) when meta partition loading local snapshot files created by older versions, skip uniqId related stuff and load will succeed;
(2) when meta partition raft leader send snapshot to followers, not send uniqId related stuff if uniqId has not been used, to avoid older version followers failure when apply snapshot.

**Comment by Victor1319** [comment]
Good idea.
