### ISSUE TITLE
[Feature]: Cross-az data repair traffic optimization for blobstore

### ISSUE THREAD

**Issue by JasonHu520** [cubefs/cubefs#2377]
**Is your feature request related to a problem? Please describe.**
Repairing the RS encoding after a bad disk will occupy cross-AZ traffic, but using LRC will increase storage redundancy in blobstore

**Describe the solution you'd like**
Calculate  the partial state of the data in the az , instead of transmitting the full amount of data, thereby reducing the traffic across az

**Comment by xiangcai1215** [comment]
Yes， this is a very important feature for which not want use LRC but want reduce cross-AZ traffic
