### ISSUE TITLE
[Bug]: Log can not cleared in a timely manner

### ISSUE THREAD

**Issue by shuqiang-zheng** [cubefs/cubefs#2399]
**Describe the bug**
The current log service may not be able to clean up the log files in a timely manner, in most cases when the log service is started，it will take the twenty percent of current disk available space as logLeftSpaceLimit, but when the current disk space  available is small and at this time the service happens to restart, the logLeftSpaceLimit now will bealso  very small, which may result in the existence of a large number of logs can not be deleted!
**Environment**
develop-3.3.0

**To Reproduce**

**Expected behavior**
The logging service should start with a minimum LogLeftSpaceLimit to ensure that log deletion can be triggered if the available space is less than this value.

**Additional context**

**Comment by true1064** [comment]
already merged into branch master
