### ISSUE TITLE
[Feature]: support set volume read only.

### ISSUE THREAD

**Issue by Victor1319** [cubefs/cubefs#2477]
**Is your feature request related to a problem? Please describe.**
In some case, want to migrate data from one volume to another,  if there are new write request in migration, which maybe lost for new changes.
So support set volume status to rdonly, so all new write operation will be failed.

**Describe the solution you'd like**
Set volume status to rdonly, datanode & metanode can get this status, and then will reject new reject new write request.

**Describe alternatives you've considered**

**Additional context**

**Comment by true1064** [comment]
tha's a good idea

**Comment by true1064** [comment]
Add an application scenarios of this featrure (from https://github.com/cubefs/cubefs/issues/2528):
For online operations, volume writes need to be restricted in abnormal scenarios, and it does not depend on the client, requiring complete controllability in the background
