### ISSUE TITLE
[Feature]:  S3API QoS

### ISSUE THREAD

**Issue by tangdeyi** [cubefs/cubefs#2478]
Support bandwidth/qps/concurrent flow control of different s3api at user level.

Through this feature, the quality of service of the system is guaranteed and it is prevented from being affected by abnormal traffic.

**Comment by true1064** [comment]
This feature is desirable

**Comment by tangdeyi** [comment]
> This feature is desirable

Yes, this feature will be released in version 3.4.0

**Comment by tangdeyi** [comment]
done
