### ISSUE TITLE
[Feature]: Support delete volume only when dentry count is zero.

### ISSUE THREAD

**Issue by Victor1319** [cubefs/cubefs#2481]
**Is your feature request related to a problem? Please describe.**
 Currently, volumes support direct deletion, even if there is still data inside the volume. There is a high risk of accidental deletion.

**Describe the solution you'd like**
The ability to delete a volume is supported only when the number of dentries inside the volume is zero.

**Comment by true1064** [comment]
good idea

**Comment by NaturalSelect** [comment]
This problem still exists?

**Comment by Victor1319** [comment]
yes, still exist @NaturalSelect

**Comment by NaturalSelect** [comment]
> yes, still exist @NaturalSelect

Hello @Victor1319.

My understanding is that the volume's dentry count is checked by the Master when mark delete volume.

Please point out any misunderstandings on my part.

**Comment by Victor1319** [comment]
yes, before delete volume, check dentry count whether zero or not on master.

**Comment by chenzufei** [comment]
I would like to participate in resolving this issue.

**Comment by jiangbbaoyu** [comment]
This is my solution,  fetch latest dentry count of the deleting volume from metaNode , if dentry count greater than zero , abort the delete operation   https://github.com/cubefs/cubefs/pull/2724.  My first try on cubeFS, any problem please contact me.  @Victor1319

**Comment by jaxjiangg** [comment]
resolved ?
