### ISSUE TITLE
[Bug]: After the quota is opened, apply panics

### ISSUE THREAD

**Issue by baijiaruo** [cubefs/cubefs#2484]
**Describe the bug**
When executing the apply operation, the panic is in：
`func (mw *MetaWrapper) applyQuota(parentIno uint64, quotaId uint32, totalInodeCount *uint64, curInodeCount *uint64, inodes *[]uint64,
maxInodes uint64, first bool) (err error)

from = entries[len(entries)-1].Name`
len(entries) is 0,cause index out of range [-1]
**Environment**
Describe your server system version, kernel version

**To Reproduce**

**Expected behavior**

**Additional context**

**Comment by true1064** [comment]
seem to be a quick fix
