### ISSUE TITLE
[Enhancement]: Some problems encountered during the integration of cubefs sdk into clickhouse cmake compilation

### ISSUE THREAD

**Issue by RunningXie** [cubefs/cubefs#2500]
### Is there an existing issue for this?

- [X] I have searched all the existing issues

### What would you like to be added?

1. Generate sdk static library file
2. The naming format of variables does not meet the requirements of gcc 4.9+ ( xxx is reserved because it starts with '_' followed by a capital letter [-Werror,-Wreserved-identifier])

**Comment by NaturalSelect** [comment]
Did you try `-Wno-error=reserved-identifier`?

**Comment by RunningXie** [comment]
> Did you try `-Wno-error=reserved-identifier`?

The reason for the problem is that there are reserved-identifier and macro-redefined errors in the header file.
To solve this problem, I use cmake to automatically add #pragma GCC diagnostic push/pop into the header file before compiling. In this way, these two types of errors can be masked.
