### ISSUE TITLE
[Feature]:  Supports write disable option（volume dimension）

### ISSUE THREAD

**Issue by leonrayang** [cubefs/cubefs#2528]
### Contact Details

changliang@oppo.com

### Is there an existing issue for this?

- [X] I have searched all the existing issues

### Is your feature request related to a problem? Please describe.

For online operations, volume writes need to be restricted in abnormal scenarios, and it does not depend on the client, requiring complete controllability in the background

### Describe the solution you'd like.

optional

**Comment by NaturalSelect** [comment]
Hello @leonrayang, I am interested in this issue.

Please let me try it.

**Comment by NaturalSelect** [comment]
Is this issue duplicate with #2477?

**Comment by true1064** [comment]
> Is this issue duplicate with #2477?

yes, it's duplicated with https://github.com/cubefs/cubefs/issues/2477

close thi9 issue

**Comment by NaturalSelect** [comment]
> > Is this issue duplicate with #2477?
> 
> yes, it's duplicated with #2477
> 
> close this issue

Ok, I will make my pull request to #2477 .
