### ISSUE TITLE
[Enhancement]: BackEnd Audit

### ISSUE THREAD

**Issue by leonrayang** [cubefs/cubefs#2625]
### Contact Details

chl696@sina.com

### Is there an existing issue for this?

- [X] I have searched all the existing issues

### What would you like to be added?

Currently, we have client-side audit functionality implemented, where the client is responsible for logging and collecting data, which is then aggregated and displayed in the data center. However, this solution has some noticeable drawbacks. For example, client upgrades may not be timely, and issues such as container exceptions or network partitions may result in unclear log reporting, making problem analysis and follow-up difficult.

To address these challenges, we want to implement server-side log statistics. Leveraging the existing implementation on the client side, we will include path information when notifying the metanode to modify metadata. The metanode will then be responsible for recording audit logs, enabling log collection and reporting on the backend.

**Comment by NaturalSelect** [comment]
Hello @leonrayang.

Can you tell me why this feature is useful? 

And I want to know what information need to be collected.

**Comment by leonrayang** [comment]
> Hello @leonrayang.
> 
> Can you tell me why this feature is useful?
> 
> And I want to know what information need to be collected.

client upgrades may not be timely, and issues such as container exceptions or network partitions may result in unclear log reporting, making problem analysis and follow-up difficult.
客户端在业务测，经常使用容器，异常情况可能丢失审计数据，上报也未必及时，服务端在存储测，审计数据不会缺失
