### ISSUE TITLE
Add case study

### ISSUE THREAD

**Issue by Vivian7755** [cubefs/cubefs#265]

**Comment by mervinkid** [comment]
User case topic has been included in document site, see [ChubaoFS User Case](https://chubaofs.readthedocs.io/en/latest/use-case.html).

**Comment by true1064** [comment]
User case topic has been included in document site:
https://cubefs.io/zh/docs/master/overview/introduction.html#%E5%BA%94%E7%94%A8%E5%9C%BA%E6%99%AF

or blogs:
https://cubefs.io/zh/blog
