### ISSUE TITLE
[Bug]: Restart objectnode, the output log will print meaningless err

### ISSUE THREAD

**Issue by baijiaruo** [cubefs/cubefs#2703]
### Is there an existing issue for this?

- [X] I have searched all the existing issues

### Priority

low (Default)

### Environment

```markdown
- CubeFS version: 3.3.0
- Deployment mode(docker or standalone or cluster):
- Dependent components:
- OS kernel version(Ubuntu or CentOS):
- CPU/Memory:
- Others:
```

### Current Behavior

Restart objectnode, the output log will print :
“2023/10/24 10:01:33  server start success, pid 569542, role objectnode"
"2023/10/24  15:00:01 err()” 

Please optimize invalid information

**Comment by HuangQAQ** [comment]
@baijiaruo Please let me try，thank you！

**Comment by leonrayang** [comment]
@tangdeyi
