### ISSUE TITLE
[Bug]: After a disk is offline, you can query disk information through the api

### ISSUE THREAD

**Issue by zhongwenqin** [cubefs/cubefs#2777]
### Contact Details

30685173@qq.com

### Is there an existing issue for this?

- [X] I have searched all the existing issues

### Priority

low (Default)

### Environment

```markdown
- CubeFS version:v3.3.0
- Deployment mode(docker or standalone or cluster):cluster
- Dependent components:
- OS kernel version(Ubuntu or CentOS): euleros   5.10.0-60.18.0.50.h592
- CPU/Memory:  16G
- Others:
```

### Current Behavior

When I offline disk /data0， I checked curl -v "http://master2:17320/disks" and found that the disk was still there

**Comment by NaturalSelect** [comment]
It seem that `TryDecommissionDisk` just offline add data partitions on disk?

I have a solution of this problem:
1.  Add `DecommissionDisk` pattern to `DeleteDataPartitionRequest`.
2.  If a disk be decommissioned, we will set its `DeleteDataPartitionRequest::DecommissionDisk` to true when offline data partitions.
3.  When datanode receive this request, it will mark disk to be decommission, and if disk's data partition count is 0, disk
 will be decommissioned and not show in `/disks` api.
4. If a datanode receive a `CreateDataPartitionRequest` to place a partition to decommissioned disk(in datanode'
s view), the datanode will know it's decommission status is not up-to-date and make the disk online.

Please point out any mistakes or misunderstandings on my part.
