### ISSUE TITLE
[Enhancement]: support multiple datanode/metanode instances using different port on a single node 

### ISSUE THREAD

**Issue by morphes1995** [cubefs/cubefs#3004]
### Contact Details

morphes1995@gmail.com

### Is there an existing issue for this?

- [x] I have searched all the existing issues

### What would you like to be added?

For a specified data partition or meta partition , currently, the replica members must use the same raft heartbeat port and replica port, otherwise replicas will not be able to communicate with each other.

```go
func (mp *metaPartition) startRaft() (err error) {
  heartbeatPort, replicaPort, err = mp.getRaftPort() // all peers of this mp use same port
	for _, peer := range mp.config.Peers {
		rp := raftstore.PeerAddress{
			HeartbeatPort: heartbeatPort,
			ReplicaPort:   replicaPort,
		}
		peers = append(peers, rp)
	}
	pc := &raftstore.PartitionConfig{
		Peers:   peers,
	}
	mp.raftPartition, err = mp.config.RaftStore.CreatePartition(pc)
  return 
}
```

### Why is this needed?

For a single node that only has one net card , in order to deploy cubeFS, we must fake some secondary IPs to satisfy the replicas  port requirement. 

### Anything else?

None yet

**Comment by morphes1995** [comment]
Another reason for this feature,  we can build a even more fully-fectured unit test system in which dn/mn not just start a http server

**Comment by xiaochunhe** [comment]
> Another reason for this feature, based on which we can build a even more fully-fectured unit test system in which dn/mn not just start a http server

good advice :) , there was a PR (https://github.com/cubefs/cubefs/pull/3016) recently to solve this problem
