### ISSUE TITLE
[Bug]:  yaml: unmarshal errors:

### ISSUE THREAD

**Issue by long1318737396** [cubefs/cubefs#3100]
### Is there an existing issue for this?

- [X] I have searched all the existing issues

### Priority

low (Default)

### Environment

```markdown
- CubeFS version:
v3.3.0
- Deployment mode(docker or standalone or cluster):
docker
- Dependent components:
- OS kernel version(Ubuntu or CentOS):
centos Linux 4.18.0-477.13.1.0.1.an8.x86_64
- CPU/Memory: 4vcpu/8G
- Others:
```

### Current Behavior

this is my setup:
git clone https://github.com/cubefs/cubefs.git
cd cubefs
make
when i sh ./shell/depoly.sh /data/cubefs eth0  this is secuess
then 
sh ./shell/stop.sh
./docker/run_docker.sh -r -d /data/cubefs
but this is fail

### CubeFS Log

![image](https://github.com/cubefs/cubefs/assets/116941376/e56ffc66-f3ae-4c7f-a58e-6f33400fa927)

**Comment by cuixiaojun001** [comment]
I have encountered a similar issue. When using Docker for a quick start, I also encountered a YAML error. Is there a solution for this?

**Comment by heymingwei** [comment]
this will happen with new version of docker-compose, because yaml will not allowd to be like an array of "<<".
