### ISSUE TITLE
[Bug]: datanode consumes high memory when upload file using s3cmd

### ISSUE THREAD

**Issue by morphes1995** [cubefs/cubefs#3156]
### Is there an existing issue for this?

- [X] I have searched all the existing issues

### Priority

high

### Environment

```markdown
- CubeFS version: master
- Deployment mode(docker or standalone or cluster):cluster
- Dependent components: dn
- OS kernel version(Ubuntu or CentOS): ubuntu
- CPU/Memory: 4c/8G
- Others:
```

### Current Behavior

datanode consumes high memory when upload file using s3cmd,  and dn may be  killed if it has a poor memory capacity
![image](https://github.com/cubefs/cubefs/assets/155799371/1c87040a-fb33-4688-9acf-58b227c81701)

<img width="860" alt="image" src="https://github.com/cubefs/cubefs/assets/155799371/336441ad-da31-4ac1-98db-c361f0ca8ad8">

when uploading file, i use pprof to monitor the  heap usage, and it seems like that there are some packet.Data  don't released,
![image](https://github.com/cubefs/cubefs/assets/155799371/b8dc3f52-1aad-421d-9aa9-e7223fb808d8)
![image](https://github.com/cubefs/cubefs/assets/155799371/fe60b9c5-4abc-434c-b631-c26d28a25ab5)

### Expected Behavior

when upload file, memory consumed by dn in a normal level

**Comment by morphes1995** [comment]
i think i found the reason
1)  in function ReadFromConnWithVer, using make to allocate memory for packet.Data
```go
p.Data = make([]byte, size)
``` 
2) when the packet processed, it need to be clean.  And clean function put the packet.Data to BufferPool. Process of every packet with util.BlockSize  need to allocate new memory but go GC can't  recycle them which cause dn memory usage increase !
```go
func (p *Packet) clean() {
	if p.OrgBuffer != nil && len(p.OrgBuffer) == util.BlockSize && p.IsNormalWriteOperation() {
		proto.Buffers.Put(p.OrgBuffer)
	}
}
``` 
3) According to v3.3.0 ReadFromConnFromCli , i fixed this issue https://github.com/cubefs/cubefs/pull/3157
```go
if p.IsWriteOperation() && readSize == util.BlockSize {
		p.Data, _ = proto.Buffers.Get(readSize)
	} else {
		p.Data = make([]byte, readSize)
	}
	_, err = io.ReadFull(c, p.Data[:readSize])
	return
```

**Comment by true1064** [comment]
we are checking this out.
thanks!
