### ISSUE TITLE
[Enhancement]: Protect MetaPartition `UpdateXAttr` interface

### ISSUE THREAD

**Issue by NaturalSelect** [cubefs/cubefs#3177]
### Contact Details

huangzhibin1@oppo.com

### Is there an existing issue for this?

- [X] I have searched all the existing issues

### What would you like to be added?

Currently, interface `UpdateXAttr` does not perform any parameter checking.

Add checks for `newValueList` parameter and check the result of `strconv.ParseInt`.

**Comment by guojidan** [comment]
let me try implement this
