### ISSUE TITLE
[Enhancement]: rocksdb数据丢失的情况下如何通过shard header中保存的备份恢复元数据

### ISSUE THREAD

**Issue by BillXiang** [cubefs/cubefs#3278]
### Is there an existing issue for this?

- [X] I have searched all the existing issues

### What would you like to be added?

https://mp.weixin.qq.com/s?__biz=Mzg4OTczODE2Ng==&mid=2247484239&idx=1&sn=bd4d7cce7f6dcae2d786a350dc170e26&chksm=cfe60596f8918c80e10f6751b1821fb5fcb540e148ce1cb0126464d3845336485c7088733412&scene=178&cur_album_id=2650171471021195265#rd
看上面文档说可以,能否提供一下相关操作说明,谢谢

### Why is this needed?

确保出问题的情况下可以恢复

**Comment by JasonHu520** [comment]
Thanks for raising this question. We had planned to do it before, but never did it. We will arrange time to complete the tools and operating documents later, current problem can be solved by repairing the bad disk or dropping machine.

**Comment by BillXiang** [comment]
ok, thanks for reply

**Comment by Cloudstriff** [comment]
单节点的rocksdb元数据丢失，建议直接走坏盘修复即可，步骤最少也最简单全自动化，不容易出错。如果担心多节点的rocksdb元数据丢失，可以考虑调整EC编码模式来规避，采用冗余度较大或者扇出较大的编码模式，比如单AZ 12+5、12+6等等，通过可靠性的提升来规避该问题。
