### ISSUE TITLE
[Enhancement]: Client supports sending three copies to datanode on RDMA mode now

### ISSUE THREAD

**Issue by aaronwu2010** [cubefs/cubefs#3381]
### Contact Details

wuhuocheng@oppo.com

### Is there an existing issue for this?

- [X] I have searched all the existing issues

### What would you like to be added?

I would like to add one feature that sending out three copies from client. It avoid the datapath from leader to follower.

### Why is this needed?

It is hard to improve the datanode performance. If the client sends out 3 data copies at the same time, the response delay is lower.
The performance is 30% higher.

### Anything else?

Is there any issues in such design?

**Comment by jadewang198510** [comment]
This is a good idea and we already have plans to support this feature

**Comment by aaronwu2010** [comment]
1. We have add such feature into RDMA mode if the traffic is under 300MB/s。
2. For large traffic, such traffic costs 3 times network resource than before. For example, it is 3.1GB/s in 25Gbps network device. If 3 copies sends, the total use speed is under 1GB/s. It is much less than the old result 2.2GB/s。So it is disabled if the total traffic goes up 300MB/s.
3. It works ok with our test script.

**Comment by aaronwu2010** [comment]
Add the design diagram in attached file

**Comment by aaronwu2010** [comment]
We release a beta version on branch release-oppo-beta-rdma-3.4.0.
