### ISSUE TITLE
[Enhancement]: When calling `auditlog.LogDentryOp` and `auditlog.LogInodeOp`, we should pass in microseconds as the `latency` parameter

### ISSUE THREAD

**Issue by yuangcao** [cubefs/cubefs#3444]
### Contact Details

cyadxx@mail.ustc.edu.cn

### Is there an existing issue for this?

- [X] I have searched all the existing issues

### What would you like to be added?

Now these functions are called like this:

```golang
auditlog.LogInodeOp(..., time.Since(start).Milliseconds(), ...)
```

But the latency recorded in the auditlog file is in microseconds. It should be changed to:

```golang
auditlog.LogInodeOp(..., time.Since(start).Microseconds(), ...)
```

### Why is this needed?

The type of the `latency` parameter in `auditlog.LogInodeOp` is `int64`. If `time.Since(start).Milliseconds()` is passed to it, it will be rounded up. In most cases, the latency is less than 1 ms, so the input will be 0.xxx and it will be rounded to 0 or 1. In this situation, the latency recorded in auditlog will be 0 or 1 and it's inaccurate.

**Comment by leonrayang** [comment]
@yuangcao Please close the issue if you have fix it .
