### ISSUE TITLE
[Bug]: yum部署createvol报owner not found

### ISSUE THREAD

**Issue by songyao199681** [cubefs/cubefs#3448]
### Contact Details

sy1132197391@163.com

### Is there an existing issue for this?

- [X] I have searched all the existing issues

### Priority

low (Default)

### Environment

```markdown
./cfs-cli -v
CubeFS CLI
Version : v3.3.0
Branch  : heads/v3.3.0
Commit  : 3d9f15e4cf21e1b7599fed5239d67f4e092f5d4f
Build   : go1.17.12 linux amd64 2023-09-20 12:05

 cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

cpu/内存：2C2G
```

### Current Behavior

执行bash install.sh -r createvol卡住了，然后我手动执行创建卷的结果报错如下：
 curl  http://10.0.0.128:17010/admin/createVol?name=ltptest&capacity=5&owner=ltptest
  {"code":2,"msg":"[operate_util.go 182] parameter owner not found","data":null}

### Steps To Reproduce

```markdown
curl  http://10.0.0.128:17010/admin/createVol?name=ltptest&capacity=5&owner=ltptest
  {"code":2,"msg":"[operate_util.go 182] parameter owner not found","data":null}
```

**Comment by leonrayang** [comment]
@songyao199681 The curl url need include by "" as curl  "http://10.0.0.128:17010/admin/createVol?name=ltptest&capacity=5&owner=ltptest"

**Comment by songyao199681** [comment]
> @songyao199681 The curl urlneeds to be enclosed in quotes, like "http://10.0.0.128:17010/admin/createVol?name=ltptest&capacity=5&owner=ltptest"curl url需要用引号括起来，比如“[http://10.0.0.128:17010/admin/createVol? name=ltptest& capacity=5& owner=ltptest](http://10.0.0.128:17010/admin/createVol?name=ltptest&capacity=5&owner=ltptest)“

问题解决了，我的内存是2G，metanode内存是调成70%虽然可以起来，但是你们开发说需要预留1G内存，导致metanode不可写，我换成4G了，metanode可写，调接口创建volume可以了。
