### ISSUE TITLE
[Bug]: if volume name not match regexp when mounted, return failed immediately

### ISSUE THREAD

**Issue by longerfly** [cubefs/cubefs#3522]
### Is there an existing issue for this?

- [X] I have searched all the existing issues

### Priority

low (Default)

### Environment

```markdown
- CubeFS version:3.4.0
```

### Current Behavior

when mounting a volume and the name is not match the regexp,  return failed immediately. Current  behaivor is  to retry,  until reached max retry times.

**Comment by bboyCH4** [comment]
close by https://github.com/cubefs/cubefs/pull/3555
