### ISSUE TITLE
[Feature]: A linux kernel client module for cubefs

### ISSUE THREAD

**Issue by aaronwu2010** [cubefs/cubefs#3571]
### Contact Details

wuhuocheng@oppo.com

### Is there an existing issue for this?

- [X] I have searched all the existing issues

### Is your feature request related to a problem? Please describe.

NO

### Describe the solution you'd like.

Rewrite the client on linux c language.
It has the same behavior as fuse client.

### Describe an alternate solution.

No. Of cause, the fuse client is ready now.

### Anything else? (Additional Context)

N/A

**Comment by leonrayang** [comment]
+1

**Comment by aaronwu2010** [comment]
Push codes to branch develop-v3.6.0-kernel-rdma2
