### ISSUE TITLE
ec :alloc volume error:no available volume

### ISSUE THREAD

**Issue by biao-lvwan** [cubefs/cubefs#3592]
### Is there an existing issue for this?

- [X] I have searched all the existing issues

### Priority

fatal

### Environment

```markdown
cubefs 3.3.2
```

### Current Behavior

The volume that cannot use ec

### CubeFS Log

I have a few questions. 
1. Why does an error appear when starting clustermgr when no volume is created?
2. Each node of the blobnode must have a disk limit?
3. Registered a test-cold volume and checked the status. The available volume is still 0.

1, The following is a screenshot of the log:

2024/12/07 23:42:01.384953 [ERROR] blobstore/clustermgr/diskmgr/alloc.go:109 [217984a109302b06:a35330ac1b5aa1de] alloc from idc allocator failed, err:no enough space to alloc
2024/12/07 23:42:01.384963 [ERROR] blobstore/clustermgr/diskmgr/diskmgr.go:507 [217984a109302b06:a35330ac1b5aa1de] create volume alloc first time failed, err: no enough space to alloc
2024/12/07 23:42:01.384986 [ERROR] blobstore/clustermgr/volumemgr/volumemgr.go:747 [217984a109302b06:b6e57fb6836f2bc9] finish last create volume job failed ==>  --> blobstore/clustermgr/volumemgr/createvolume.go:90 no enough space to alloc ~ alloc chunk for volume unit failed
2024/12/07 23:42:02.043349 [INFO] blobstore/clustermgr/base/raftnode.go:493 [raft-node-loop:6b38c58eef3afdd5] raft node flush all raft applier cost: 0 ms, flush all dbs cost: 0 ms, save apply index cost: 0 ms, truncate log cost: 0 ms
2024/12/07 23:42:02.458059 [INFO] blobstore/clustermgr/manage.go:119 [f98fbe11ff0ae1a6:d3d0f22f3a677a6b] accept Stat request
2024/12/07 23:42:05.456493 [INFO] blobstore/clustermgr/manage.go:119 [18b7c537874b3b52:bea76a971ea5c3a8] accept Stat request
2024/12/07 23:42:08.032805 [INFO] blobstore/clustermgr/diskmgr/refresh.go:290 [0d1be229aa060f84:8fb8ab79c4fd690f] z0 idcBlobNodeStgs length: 1
2024/12/07 23:42:08.032882 [INFO] blobstore/clustermgr/diskmgr/refresh.go:290 [0d1be229aa060f84:8fb8ab79c4fd690f] z0 idcBlobNodeStgs length: 1
2024/12/07 23:42:08.460168 [INFO] blobstore/clustermgr/manage.go:119 [6c749fd04895a13d:dfb67dbedea3ba11] accept Stat request
2024/12/07 23:42:11.387482 [INFO] blobstore/clustermgr/volumemgr/alloc.go:324 [dea2a80adb2daa65:aa072598fef0af26] optional vids length is 0, vids is []
2024/12/07 23:42:11.387583 [ERROR] blobstore/clustermgr/volume.go:116 [dea2a80adb2daa65:aa072598fef0af26] alloc volume error:no available volume
2024/12/07 23:42:11.388924 [INFO] blobstore/clustermgr/diskmgr/alloc.go:581 [217984a109302b06:8fab8e03cafbcc12] z0 retry choose with same host
2024/12/07 23:42:11.388959 [INFO] blobstore/clustermgr/diskmgr/alloc.go:581 [217984a109302b06:8fab8e03cafbcc12] z0 retry choose with same host
2024/12/07 23:42:11.388965 [INFO] blobstore/clustermgr/diskmgr/alloc.go:581 [217984a109302b06:8fab8e03cafbcc12] z0 retry choose with same host
2024/12/07 23:42:11.388976 [INFO] blobstore/clustermgr/diskmgr/alloc.go:581 [217984a109302b06:8fab8e03cafbcc12] z0 retry choose with same host
2024/12/07 23:42:11.388982 [INFO] blobstore/clustermgr/diskmgr/alloc.go:581 [217984a109302b06:8fab8e03cafbcc12] z0 retry choose with same host
2024/12/07 23:42:11.388987 [INFO] blobstore/clustermgr/diskmgr/alloc.go:581 [217984a109302b06:8fab8e03cafbcc12] z0 retry choose with same host
2024/12/07 23:42:11.389007 [WARN] blobstore/clustermgr/diskmgr/alloc.go:362 [217984a109302b06:8fab8e03cafbcc12] alloc failed, chosenRacks: map[], chosenBlobNodeStorages: map[0xc00067c780:1], chosenDisks: map[1:0xc00045b5c0]

2,http://192.168.*.*:9998/stat)
{
    "leader_host": "clustermgr-0.clustermgr-service::9998",
    "read_only": false,
    "raft_status": {
        "nodeId": 1,
        "term": 1,
        "vote": 1,
        "commit": 130,
        "leader": 1,
        "raftState": "StateLeader",
        "applied": 130,
        "raftApplied": 130,
        "transferee": 0,
        "applyingLength": 0,
        "peers": [
            {
                "id": 1,
                "host": "clustermgr-0.clustermgr-service:10110",
                "match": 130,
                "next": 131,
                "state": "StateReplicate",
                "paused": false,
                "pendingSnapshot": 0,
                "active": true,
                "isLearner": false,
                "isInflightFull": false,
                "inflightCount": 0
            }
        ]
    },
    "space_stat": {
        "total_space": 1034550247424,
        "free_space": 1026849312768,
        "readonly_space": 0,
        "used_space": 7700934656,
        "writable_space": 513382809600,
        "total_blob_node": 1,
        "total_disk": 1,
        "disk_stat_infos": [
            {
                "idc": "z0",
                "total": 1,
                "total_chunk": 61664,
                "total_free_chunk": 61204,
                "available": 1,
                "readonly": 0,
                "expired": 0,
                "broken": 0,
                "repairing": 0,
                "repaired": 0,
                "dropping": 0,
                "dropped": 0
            }
        ]
    },
    "volume_stat": {
        "total_volume": 0,
        "idle_volume": 0,
        "can_alloc_volume": 0,
        "active_volume": 0,
        "lock_volume": 0,
        "unlocking_volume": 0
    }
}

3,
![image](https://github.com/user-attachments/assets/fb31d498-9141-408e-b3c8-f0a6a79c41b7)

### Anything else? (Additional Context)

wwww

**Comment by sejust** [comment]
@biao-lvwan  There only one disk registered, need more on EC mode.

**Comment by biao-lvwan** [comment]
> 只有一个注册的磁盘，需要更多 EC 模式。

Can you help me explain in detail?To use EC3P3, you need at least 6 disks. Is there any other strategy that can be tested with one disk?

**Comment by sejust** [comment]
> Can you help me explain in detail?To use EC3P3, you need at least 6 disks. Is there any other strategy that can be tested with one disk?

https://cubefs.io/zh/docs/master/user-guide/blobstore.html#%E5%90%AF%E5%8A%A8-blobnode

**Comment by biao-lvwan** [comment]
> > Can you help me explain in detail?To use EC3P3, you need at least 6 disks. Is there any other strategy that can be tested with one disk?
> 
> https://cubefs.io/zh/docs/master/user-guide/blobstore.html#%E5%90%AF%E5%8A%A8-blobnode

What is mentioned above is the configuration of a single node. If I use ec3p3, do I need 6 nodes? Each node can mount one disk or multiple disk directories, or can it be one node but mount different directories?

**Comment by sejust** [comment]
> What is mentioned above is the configuration of a single node. If I use ec3p3, do I need 6 nodes? Each node can mount one disk or multiple disk directories, or can it be one node but mount different directories?

Blobnode's disk is virtual and no need to be an exact mount point. Configure multi-directories as virtual disks.

**Comment by biao-lvwan** [comment]
> > What is mentioned above is the configuration of a single node. If I use ec3p3, do I need 6 nodes? Each node can mount one disk or multiple disk directories, or can it be one node but mount different directories?
> 
> Blobnode's disk is virtual and no need to be an exact mount point. Configure multi-directories as virtual disks.

Hi, I tried it. The ec mode needs to use the corresponding number of disks. If it is in k8s, it is not possible to configure 6 directories for one node. You need to deploy 6 nodes and correspond to six disks. The question is first. closed
