### ISSUE TITLE
Feature request: soft and hard link support in object storage interface

### ISSUE THREAD

**Issue by mervinkid** [cubefs/cubefs#412]
**Is your feature request related to a problem? Please describe.**

ChubaoFS is a distributed fusion storage that provides both POSIX-compatible file system interface and S3-compatible object storage interface. 
The object storage interface is designed on the basis of POSIX compatibility, the object storage semantics will be escaped to POSIX semantics on ChubaoFS.
The object storage interface is compatible with S3, so that file system operations cannot be performed which not defined in Amazon S3 . 
For example, user cannot make soft or hard link through the object storage interface.

**Describe the solution you'd like**

Users want to make soft and hard links through the object storage interface like using `ln` command through POSIX-compatible file system interface.
This feature reuqest comes from Yuhao Zhang of the **Recommended Search Platform Division** in the JD Retail.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by tangdeyi** [comment]
The copy or part copy of existing object interface is  based on data streams and does not implement hard link, because the custom metadata of different objects may be different, and the same inode cannot save the custom metadata of different objects.
