### ISSUE TITLE
Bug report: metanode snapshot files lack of checksum verification

### ISSUE THREAD

**Issue by shuoranliu** [cubefs/cubefs#993]
**Describe the bug**
When metanode starts and loads snapshot file, there is no checksum verification. Although snapshot file length is respected, a bit-rot problem still have the chance of being undetected, and therefore metanode would starts successfully with wrong meta data.

**Environment**
N/A

**To Reproduce**
Inject a bit-rot problem to the latest metanode snapshot file, and restart metanode.

**Expected behavior**
Checksum verification of the snapshot file which is very critical.

**Additional context**
Recommend to add checksum at the end of each snapshot file, and keep backward compatibility.

**Comment by leonrayang** [comment]
release 3.3.0 will resolve the issue and the commit already in master
